//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by PROGRPT.RC
//

#ifndef __RESOURCE_H_INCLUDED
#define __RESOURCE_H_INCLUDED

#define IDR_MAINFRAME                   128
#define IDR_REPORTTYPE                  129
#define IDR_ITEMTYPE                    130
#define IDR_SHEETTYPE                   130
#define IDD_ABOUTBOX                    100
#define IDD_LIST_FORM                   101
#define IDD_LIST_PROP                   102
#define IDD_FILED_FORM                  103
#define IDD_TITLE_FORM                  104
#define IDD_PRINT_PROP                  105
#define IDD_PRINT_DETAIL                106
#define IDD_16CHAR_MNEMO                107
#define IDD_40CHAR_MNEMO                108
#define IDD_EOD_FORM                    109
#define IDD_MATHE_PROP                  110
#define IDD_IMPORT_FORM                 111
#define IDD_PTD_FORM                    112
#define IDD_LOOP_PROP                   114
#define IDD_SIZE_FORM                   119
#define IDC_REPORT_LIST                 1000
#define IDC_REPORT_NEW                  1001
#define IDC_REPORT_OPEN                 1002
#define IDC_REPORT_DELETE               1003
#define IDC_REPORT_PROP                 1004
#define IDC_LIST_PROP_FILE              1005
#define IDC_LIST_PROP_DEVICE            1006
#define IDC_FIELD_INSERT                1008
#define IDC_FIELD_CLOSE                 1009
#define IDC_LIST_PROP_TITLE             1010
#define IDC_FIELD_GROUP                 1011
#define IDC_FIELD_FIELD                 1012
#define IDC_FIELD_TOP                   1013
#define IDC_FIELD_LOOP                  1014
#define IDC_FIELD_PRINT                 1015
#define IDC_FIELD_MATHE                 1016
#define IDC_TITLE_TITLE                 1017
#define IDC_FIELD_ITEM                  1018
#define IDC_FIELD_CANCEL                1019
#define IDC_PRINT_GROUP                 1021
#define IDC_PRINT_MAJOR                 1022
#define IDC_PRINT_ITEM                  1023
#define IDC_PRINT_WIDTH                 1024
#define IDC_PRINT_FORMAT                1026
#define IDC_PRINT_RIGHT                 1028
#define IDC_PRINT_WIDE                  1029
#define IDC_PRINTD_GROUP1               1029
#define IDC_PRINT_DETAIL                1030
#define IDC_PRINTD_MAJOR1               1030
#define IDC_PRINT_MINOR                 1031
#define IDC_PRINTD_ITEM1                1031
#define IDC_PRINT_LEFT                  1032
#define IDC_PRINTD_MINOR1               1032
#define IDC_PRINT_COND                  1033
#define IDC_MATHE_MINOR1                1033
#define IDC_PRINTD_COND                 1034
#define IDC_MATHE_ITEM1                 1034
#define IDC_PRINTD_GROUP2               1035
#define IDC_PRINTD_MAJOR2               1036
#define IDC_PRINTD_MINOR2               1037
#define IDC_PRINTD_ITEM2                1038
#define IDC_16CM_LIST                   1041
#define IDC_16CM_MNEMO                  1042
#define IDC_40CM_LIST                   1045
#define IDC_40CM_MNEMO                  1046
#define IDC_MATHE_VALUE                 1047
#define IDC_MATHE_USE                   1048
#define IDC_MATHE_GROUP2                1049
#define IDC_MATHE_MAJOR2                1050
#define IDC_MATHE_MINOR2                1051
#define IDC_MATHE_ITEM2                 1052
#define IDC_MATHE_GROUP1                1053
#define IDC_MATHE_MAJOR1                1054
#define IDC_MATHE_GROUP                 1055
#define IDC_MATHE_MAJOR                 1056
#define IDC_MATHE_MINOR                 1057
#define IDC_MATHE_ITEM                  1058
#define IDC_MATHE_COND                  1059
#define IDC_EOD_STD                     1060
#define IDC_EOD_ORG                     1061
#define IDC_EOD_LIST                    1063
#define IDC_EOD_OBJECT                  1064
#define IDC_EOD_UP                      1069
#define IDC_EOD_DOWN                    1070
#define IDC_REPORT_UP                   1071
#define IDC_REPORT_DOWN                 1072
#define IDC_IMPORT_IMPORT               1073
#define IDC_IMPORT_LIST                 1074
#define IDC_PTD_STD                     1075
#define IDC_PTD_ORG                     1076
#define IDC_PTD_LIST                    1077
#define IDC_PTD_OBJECT                  1078
#define IDC_PTD_UP                      1079
#define IDC_PTD_DOWN                    1080
#define IDC_LOOP_GROUP                  1081
#define IDC_LOOP_MAJOR                  1082
#define IDC_LOOP_COND                   1086
#define IDC_SIZE_DISP                   1092
#define IDC_SIZE_ICON                   1093
#define IDC_SIZE_MESSAGE                1094
#define IDC_EOD_FILE                    1095
#define IDC_EOD_STATE                   1096
#define IDC_EOD_NO                      1097
#define IDC_EOD_DEVICE                  1098
#define IDC_EOD_TITLE                   1099
#define IDC_PTD_FILE                    1100
#define IDC_PTD_STATE                   1101
#define IDC_PTD_NO                      1102
#define IDC_PTD_DEVICE                  1103
#define IDC_PTD_TITLE                   1104
#define IDC_PRINTD_GR1                  1105
#define IDC_PRINTD_MA1                  1106
#define IDC_PRINTD_MI1                  1107
#define IDC_PRINTD_IT1                  1108
#define IDC_PRINTD_GR2                  1109
#define IDC_PRINTD_MA2                  1110
#define IDC_PRINTD_MI2                  1111
#define IDC_PRINTD_IT2                  1112
#define IDC_PRINTD_COND1                1113
#define IDC_PRINTD_COND2                1114
#define IDC_MATHE_OPE2                  1115
#define IDC_MATHE_GR1                   1116
#define IDC_MATHE_MA1                   1117
#define IDC_MATHE_MI1                   1118
#define IDC_MATHE_IT1                   1119
#define IDC_MATHE_GR2                   1120
#define IDC_MATHE_MA2                   1121
#define IDC_MATHE_MI2                   1122
#define IDC_MATHE_IT2                   1123
#define ID_SETTING_EOD                  22771
#define ID_SETTING_PTD                  22772
#define ID_SETTING_16CHAR               22773
#define ID_SETTING_40CHAR               22774
#define ID_REPORT_NEW                   22775
#define ID_REPORT_OPEN                  22776
#define ID_REPORT_PROP                  22777
#define ID_REPORT_IMPORT                22778
#define ID_REPORT_INSERTFIELD           22779
#define ID_REPORT_SETTITLE              22780
#define ID_VIEW_PRINT                   22781
#define ID_VIEW_MATHE                   22782
#define ID_EDIT_INSERTROW               22783
#define IDC_PR_SIZENS                   22985
#define IDC_PR_MOVE                     22987
#define ID_INDICATOR_SIZE               19142
#define IDS_ERRMSG_REPORTDELETE         21216
#define IDS_ERRMSG_INSERTLOOP           21217
#define IDS_ERRMSG_PEP                  21218
#define IDS_ERRMSG_RANGE                21219
#define IDS_ERRMSG_COND                 21220
#define IDS_ERRMSG_INI                  21221
#define IDS_ERRMSG_EODPTD               21222
#define IDS_ERRMSG_LCD                  21223
#define IDS_ERRMSG_VERSION              21224
#define IDS_ERRMSG_SIZE                 21225
#define IDS_STSMSG_PEP                  21226
#define IDS_STSMSG_PROGRPT              21227
#define IDS_STSMSG_CLEAR                21228
#define IDS_STSMSG_PASTE                21230
#define IDS_ERRMSG_CLIPBOARD            21231
#define IDS_STSMSG_DELROW               21232
#define IDS_ERRMSG_FILEFILED            21233
#define IDS_ERRMSG_OPEN310TO330         21234
#define IDS_ERRMSG_IMP310TO330          21235
#define IDS_ERRMSG_OPEN100TO340         21236	// ADD Saratoga

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         21237
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif

#endif
