//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DeviceConfig.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DEVICECONFIG_DIALOG         102
#define IDS_CONTROL_TYPE_IGNORE         102
#define IDS_CONTROL_TYPE_DIRECT         103
#define IDS_CONTROL_TYPE_OPOS           104
#define IDS_CONTROL_TYPE_ETHERNET       105
#define IDS_CONTROL_TYPE_NOTE           106
#define IDS_HEADING_1                   107
#define IDS_HEADING_2                   108
#define IDS_HEADING_3                   109
#define IDS_HEADING_4                   110
#define IDS_HEADING_5                   111
#define IDS_HEADING_6                   112
#define IDS_CONTROL_TYPE_DLL            113
#define IDS_CONTROL_TYPE_SPECIAL        114
#define IDS_CONTROL_TYPE_WEDGE          115
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_DEVICELIST           129
#define IDD_DIALOG_PORT_SETTINGS        130
#define IDD_DIALOG_INITIAL_RESET        131
#define IDD_DIALOG_SECRET_NUMBER        132
#define IDS_CONTROL_INT_DIRECT          133
#define IDS_CONTROL_INT_OPOS            134
#define IDS_CONTROL_INT_ETHERNET        135
#define IDS_CONTROL_INT_NOTE            136
#define IDD_DIALOG_EPT_SETTINGS         137
#define IDD_DIALOG_TEST                 138
#define IDD_DIALOG_OPOS_TEST            139
#define IDD_DIALOG_DSICLIENTX           141
#define IDD_DIALOG_DSIPDCX              143
#define IDD_DIALOG_DSIEMVUS             144
#define IDR_MENU1                       145
#define IDD_DIALOG_NETWORK_PORT         147
#define IDD_DIALOG_OPTION               150
#define IDD_OPTION_VALUE                151
#define IDD_DIALOG_COPY_CONFIRM         152
#define IDD_NHPOS_UNLOCK                153
#define IDD_DIALOG_DISCONNECTED_SAT_PARAMS 154
#define IDD_DIALOG_DATACAP_ENCRYPT      155
#define IDD_PINPAD1000DIALOG            156
#define IDD_PINPAD2000DIALOG            157
#define IDD_PINPADEVERESTDIALOG         158
#define IDD_PINPADPDCDIALOG             159
#define IDS_CONTROL_INT_DLL             160
#define IDS_CONTROL_INT_SPECIAL         161
#define IDS_CONTROL_INT_WEDGE           162
#define IDD_DIALOG_OPOS_PINPAD          163
#define IDD_DRAGDROP_DIALOG             164
#define IDD_DIALOG_USERSCRIPT           165
#define IDC_LIST_DEVICES                1000
#define IDC_CASHDRAWER1                 1000
#define IDC_VER2000XCTRL1               1001
#define IDC_LINEDISPLAY1                1001
#define IDC_BUTTON_SETTINGS             1002
#define IDC_MSR1                        1002
#define IDC_BUTTON_CHANGE_DEVICE        1003
#define IDC_POSPRINTER1                 1003
#define IDC_COMBO_PORT                  1004
#define IDC_COINDISPENSER1              1004
#define IDC_COMBO_BAUD                  1005
#define IDC_KEYLOCK1                    1005
#define IDC_COMBO_CHARBITS              1006
#define IDC_CASHDRAWER2                 1006
#define IDC_COMBO_PARITY                1007
#define IDC_COMBO_STOPBITS              1008
#define IDC_COMBO_HANDSHAKE             1009
#define IDC_STATIC_PORT                 1010
#define IDC_STATIC_BAUD                 1011
#define IDC_STATIC_CHARBITS             1012
#define IDC_STATIC_PARITY               1013
#define IDC_STATIC_STOPBITS             1014
#define IDC_STATIC_HANDSHAKE            1015
#define IDC_STATIC_IP_ADDR              1016
#define IDC_STATIC_IP_PORT              1017
#define IDC_EDIT_IP_PORT                1018
#define IDC_IPADDRESS                   1019
#define IDC_STATIC_FRAME_COMM           1020
#define IDC_STATIC_FRAME_IP             1021
#define IDC_SECRETNUM_SECRETNUM_EDIT    1023
#define IDC_SECRETNUM_SECRETNUM_STR     1024
#define IDC_INITRESET_STATIC            1025
#define IDC_INITRESET_EXIT              1026
#define IDC_INITRESET_CLEAR             1027
#define IDC_INITRESET_SELECT            1028
#define IDC_STATIC_TYPE_OF_EPT          1029
#define IDC_STATIC_INITRESET_STATUS     1029
#define IDC_STATIC_DATACAP              1032
#define IDC_STATIC_MERCURY              1033
#define IDC_MERCURY_NAMESERVER1         1034
#define IDC_MERCURY_NAMESERVER2         1035
#define IDC_STATIC_NAMESERVER1          1036
#define IDC_STATIC_NAMESERVER2          1037
#define IDC_DATACAP_NAMESERVER_IP       1039
#define IDC_DATACAP_COMM_PORT           1041
#define IDC_STATIC_COMM_PORT            1042
#define IDC_STATIC_DATACAP_NAMESERVER   1043
#define IDC_STATIC_MERCHANT_GROUP       1044
#define IDC_STATIC_MERCHANT_ID          1045
#define IDC_MERCHANT_ID                 1046
#define IDC_STATIC_DATACAP_DISPLAY      1047
#define IDC_MERCURY_COMM_PORT           1049
#define IDC_STATIC_COMM_PORT2           1050
#define IDC_KEYMANAGETYPE_ID            1051
#define IDC_MASTERKEYINDEX_ID           1052
#define IDC_WORKINGKEY_ID               1053
#define IDC_IDLEPROMPT_ID               1054
#define IDC_SHOULDROTATE_ID             1055
#define IDC_COMBO_PINPAD                1056
#define IDC_COMBO_DATACAPSECURE         1057
#define IDC_COMBO_DATACAPSECURE_EMV     1058
#define IDC_COMBO_DATACAPSECURE_PAD     1059
#define IDC_BUTTON_ENVIR                1060
#define IDC_OPOS_PRINTER_TF             1062
#define IDC_DATACAP_DSIPDCX             1063
#define IDC_DATACAP_DSICLIENTX          1064
#define IDC_OPOS_PRINTER                1065
#define IDC_COMPNAME_TF                 1066
#define IDC_OPOS_PRINTER_VERSION        1066
#define IDC_TERMNUM_ERR_TF              1067
#define IDC_IPADDR_TF                   1068
#define IDC_STATIC_SERIALNUMBER         1069
#define IDC_VERSIONNUMBER_TF            1070
#define IDC_NHPOS_STARTUP               1071
#define IDC_EDIT_NETWORK_PORT           1072
#define IDC_NHPOS_DISCONNECTED_SAT      1073
#define IDC_NHPOS_DISCONNECTED_SAT_JOINED 1074
#define IDC_NHPOS_HTTPSERVER            1075
#define IDC_LIST_OPTIONS                1076
#define IDC_NHPOS_CONNENGINE            1076
#define IDC_CHANGE_OPTIONS              1077
#define IDS_HEADING_9                   1077
#define IDS_HEADING_7                   1078
#define IDC_EDIT_OPTIONS                1078
#define IDS_HEADING_8                   1079
#define IDC_OPTION_CHANGE               1079
#define IDC_APPLY                       1080
#define IDC_COPY_CONFIRM_YESALL         1081
#define IDC_COPY_CONFIRM_NOALL          1082
#define IDC_COPY_CONFIRM_INFO           1083
#define IDC_COPY_CONFIRM_PROP           1084
#define IDD_PROGRESS_DIALOG             1085
#define IDC_PROGRESS_INDIC              1086
#define IDC_SOFTLOCX6CTRL1              1087
#define IDC_STATIC_DAYSLEFT             1088
#define IDC_STATIC_TERMINALSERIALNO     1089
#define IDC_STATIC_SOFTWARESERIALNO     1090
#define IDC_STATIC_UNLOCKCODE           1091
#define IDC_STATIC_STATUS               1092
#define IDC_BUTTON_REGISTER_UNLOCK      1093
#define IDC_EDIT_UNLOCKNUMBER           1094
#define IDC_STATIC_SYSTEMCLASS          1095
#define STOREFORWARDCHECK               1096
#define IDC_EDIT_USERNAME               1096
#define STOREFORWARD_EDIT               1099
#define IDC_BUTTON_DISCONNECTED_SAT_PARAMS 1100
#define IDC_EDIT_DISCONNECTED_SAT_MASTER 1101
#define IDC_DATACAP_ENCRYPT_TF          1102
#define IDC_VER1000XCTRL                1103
#define IDC_PDCXCTRL1                   1104
#define IDC_IND_VER1000XCTRL            1105
#define IDC_IND_VER2000XCTRL            1106
#define IDC_IND_PDCXCTRL1               1107
#define IDC_IND_EVERESTMULTIPAYXCTRL    1108
#define IDC_STATIC_GIFT_SERVER          1109
#define IDC_IND_MASTER_IP               1109
#define IDC_STATIC_NAMESERVER3          1110
#define IDC_STATIC_NAMESERVER4          1111
#define IDC_GIFTCARD_NAMESERVER1        1112
#define IDC_GIFTCARD_NAMESERVER2        1113
#define IDC_RADIO_STANDARD_SATELLITE    1114
#define IDC_STATIC_EPD_SERVER           1114
#define IDC_RADIO_DISCONNECTED_SATELLITE 1115
#define IDC_STATIC_NAMESERVER5          1115
#define IDC_LOCKIT1                     1116
#define IDC_EPD_NAMESERVER1             1116
#define IDC_RADIO_DISCONNECTED_OVERRIDE 1116
#define IDC_EDIT_CONNENGINE_PORT        1117
#define IDC_STATIC_NAMESERVER6          1117
#define IDC_NHPOS_HTTPSERVER_PORT       1118
#define IDC_EPD_NAMESERVER2             1118
#define IDC_STATIC_BC_SERVER            1119
#define IDC_STATIC9                     1119
#define IDC_STATIC_NAMESERVER7          1120
#define IDC_BC_NAMESERVER1              1121
#define IDC_STATIC_NAMESERVER8          1122
#define IDC_BC_NAMESERVER2              1123
#define IDC_EDIT_NEW_RESELLER_ID        1124
#define IDC_STATIC_SERIALNUMBER1        1125
#define IDC_STATIC_RESELLER_ID          1126
#define IDC_STATIC_SERIALNUMBER2        1127
#define IDC_STATIC_RESELLER_ID2         1128
#define IDC_BUTTON_GENERATE             1129
#define IDC_BUTTON_SET_RESELLER_ID      1130
#define IDC_STATIC_VALIDATE_GEN         1131
#define IDC_STATIC_VALIDATE_GEN2        1132
#define IDC_STATIC_VALIDATE_DROP        1133
#define IDC_STATIC_NAME                 1134
#define IDC_STATIC_RESELLER_LABEL       1135
#define IDC_STATIC_RESELLER_ID_LABEL    1136
#define IDC_EDIT1                       1137
#define IDC_BUTTON0                     1138
#define IDC_BUTTON1                     1139
#define IDC_BUTTON2                     1140
#define IDC_BUTTON3                     1141
#define IDC_BUTTON4                     1142
#define IDC_BUTTON5                     1143
#define IDC_BUTTON6                     1144
#define IDC_BUTTON7                     1145
#define IDC_BUTTON8                     1146
#define IDC_BUTTON9                     1147
#define IDC_BUTTON_CLEAR                1148
#define IDC_BUTTON10                    1149
#define IDC_BUTTON_FETCH                1149
#define IDC_STATIC_PORTAL_URL           1150
#define IDC_STATIC_TERM_LABEL           1151
#define IDC_STATIC_MASTER_IP            1152
#define IDC_PING_TEST                   1153
#define IDC_STATIC_USBSTART             1154
#define IDC_CHECK_USBSTOR               1155
#define IDC_CHECK_ADD_USB_PERM          1156
#define IDC_EDIT_TERMINALID_EMV         1158
#define IDC_CHECK_IP_PORT               1159
#define IDC_BUTTONDASH                  1160
#define IDC_BUTTON_SET_SERIAL_NO        1161
#define IDC_CHECK_DSIPDCX               1162
#define IDC_CHECK_DSIEMVUS              1163
#define IDC_EVERESTMULTIPAYXCTRL1       7000
#define IDI_CLSFOLD                     7002
#define IDI_BLANK                       7003
#define IDI_FLOPPY                      7004
#define IDI_DRIVE                       7005
#define IDI_CDDRIVE                     7006
#define IDD_LIST_DIALOG                 7007
#define IDC_LIST                        7008
#define IDC_STATIC_ADDRESS              7009
#define IDC_BACK_BUTTON                 7010
#define IDC_DRIVE_COMBO                 7011
#define IDC_FILE_NAME_BOX               7012
#define IDC_FILE_NAME_TXT               7013
#define IDC_DSICLIENTXCTRL1             18001
#define IDC_DSIENCRYPTXCTRL1            18002
#define IDC_DSIPDCXCTRL1                18003
#define IDC_DSIEMVXCTRL1                18004
#define IDS_INITRESET__WARNING          20000
#define IDS_INITRESET_PERFORM_RESET     20001
#define IDS_INITRESET_PERFORM_NOLAY     20002
#define IDS_INITRESET_PERFORM_TOTAL     20003
#define IDS_INITRESET_PERFORM_GCF       20004
#define IDS_INITRESET_PERFORM_PLU       20005
#define IDS_INITRESET_PERFORM_TOTALUPD  20006
#define IDS_INITRESET_PERFORM_EEPTSTO   20007
#define IDS_ENTSECNO_ERR_MSG            20008
#define IDS_INITRESET_ERR_MSG           20009
#define IDM_INITIAL_RESET               32771
#define IDM_TEST_ENVIRONMENT            32772
#define IDS_NETWORK_PORT                32777
#define IDC_PDC_CHECK                   32778
#define IDC_STATIC_PDC                  32779
#define IDC_MAGREADCOMBO                32780
#define IDC_MAG_READ_TYPE               32781
#define IDC_MAG_READ_TIMEOUT            32782
#define IDC_MAGREADEDIT                 32783
#define IDC_CHECKREADCOMBO              32784
#define IDC_CHECK_READ_TYPE             32785
#define IDC_CHECK_READ_TIMEOUT          32786
#define IDC_CHECKREADEDIT               32787
#define IDS_IMPORT_ICONS                32788
#define IDS_EXPORT_ICONS                32789
#define IDC_STATIC_STOREFORWARD         32789
#define IDM_NHPOS_UNLOCK                32790
#define ID_TERMINALUTILITIES_EXPORTACTIVESETTINGS 32791
#define ID_TERMINALUTILITIES_IMPORTACTIVESETTINGS 32792
#define ID_TERMINALUTILITIES_USER_SETUP_SCRIPT 32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1164
#define _APS_NEXT_SYMED_VALUE           7014
#endif
#endif
