#if !defined(AFX_ACTIVEFORMX_H__34E92AAF_B126_4BF0_8430_7CCC77B9E2AF__INCLUDED_)
#define AFX_ACTIVEFORMX_H__34E92AAF_B126_4BF0_8430_7CCC77B9E2AF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CActiveFormX wrapper class

class CActiveFormX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CActiveFormX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x25c91092, 0x1613, 0x11d3, { 0xaa, 0x3c, 0x0, 0xe0, 0x29, 0x1e, 0x4d, 0x4f } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void AboutBox();
	long GetTrialStatus();
	void SetPath(LPCTSTR PathName);
	void SetOrderButton(long Param1);
	CString GetProductID();
	void SetProductID(LPCTSTR lpszNewValue);
	CString GetUserName_();
	CString GetRegNumber();
	BOOL GetMakeLicense();
	void SetMakeLicense(BOOL bNewValue);
	CString GetVBOVersion();
	BOOL GetHidden();
	void SetHidden(BOOL bNewValue);
	void SetUserName(LPCTSTR UserName);
	void SetUnlockCode(LPCTSTR code);
	CString RegisterProduct();
	CString DaysRemaining();
	CString NumUses();
	CString GetCompanyName();
	void AntiCode(BOOL Value);
	void Events(BOOL Events);
	void HideScreen(BOOL Screen);
	void SetTimer(long MS);
	double DaysInstalled();
	void ExpireLicense(long Expire);
	void RevertLicense(long Revert);
	void UseBios(long Allow);
	void UseNetWork(long Allow);
	void AntiDump();
	void EnhSoftIce();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ACTIVEFORMX_H__34E92AAF_B126_4BF0_8430_7CCC77B9E2AF__INCLUDED_)
