#if !defined(AFX_OPOSPOSPRINTER_H__DB1EEE5B_68C7_4D5C_A20E_ABCF662AC4EA__INCLUDED_)
#define AFX_OPOSPOSPRINTER_H__DB1EEE5B_68C7_4D5C_A20E_ABCF662AC4EA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// COPOSPOSPrinter wrapper class

class COPOSPOSPrinter : public CWnd
{
protected:
	DECLARE_DYNCREATE(COPOSPOSPrinter)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xccb90152, 0xb81e, 0x11d2, { 0xab, 0x74, 0x0, 0x40, 0x5, 0x4c, 0x37, 0x19 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetOpenResult();
	CString GetCheckHealthText();
	BOOL GetClaimed();
	BOOL GetDeviceEnabled();
	void SetDeviceEnabled(BOOL bNewValue);
	BOOL GetFreezeEvents();
	void SetFreezeEvents(BOOL bNewValue);
	long GetOutputID();
	long GetResultCode();
	long GetResultCodeExtended();
	long GetState();
	CString GetControlObjectDescription();
	long GetControlObjectVersion();
	CString GetServiceObjectDescription();
	long GetServiceObjectVersion();
	CString GetDeviceDescription();
	CString GetDeviceName();
	long CheckHealth(long Level);
	long ClaimDevice(long Timeout);
	long ClearOutput();
	long Close();
	long DirectIO(long Command, long* pData, BSTR* pString);
	long Open(LPCTSTR DeviceName);
	long ReleaseDevice();
	BOOL GetAsyncMode();
	void SetAsyncMode(BOOL bNewValue);
	BOOL GetCapConcurrentJrnRec();
	BOOL GetCapConcurrentJrnSlp();
	BOOL GetCapConcurrentRecSlp();
	BOOL GetCapCoverSensor();
	BOOL GetCapJrn2Color();
	BOOL GetCapJrnBold();
	BOOL GetCapJrnDhigh();
	BOOL GetCapJrnDwide();
	BOOL GetCapJrnDwideDhigh();
	BOOL GetCapJrnEmptySensor();
	BOOL GetCapJrnItalic();
	BOOL GetCapJrnNearEndSensor();
	BOOL GetCapJrnPresent();
	BOOL GetCapJrnUnderline();
	BOOL GetCapRec2Color();
	BOOL GetCapRecBarCode();
	BOOL GetCapRecBitmap();
	BOOL GetCapRecBold();
	BOOL GetCapRecDhigh();
	BOOL GetCapRecDwide();
	BOOL GetCapRecDwideDhigh();
	BOOL GetCapRecEmptySensor();
	BOOL GetCapRecItalic();
	BOOL GetCapRecLeft90();
	BOOL GetCapRecNearEndSensor();
	BOOL GetCapRecPapercut();
	BOOL GetCapRecPresent();
	BOOL GetCapRecRight90();
	BOOL GetCapRecRotate180();
	BOOL GetCapRecStamp();
	BOOL GetCapRecUnderline();
	BOOL GetCapSlp2Color();
	BOOL GetCapSlpBarCode();
	BOOL GetCapSlpBitmap();
	BOOL GetCapSlpBold();
	BOOL GetCapSlpDhigh();
	BOOL GetCapSlpDwide();
	BOOL GetCapSlpDwideDhigh();
	BOOL GetCapSlpEmptySensor();
	BOOL GetCapSlpFullslip();
	BOOL GetCapSlpItalic();
	BOOL GetCapSlpLeft90();
	BOOL GetCapSlpNearEndSensor();
	BOOL GetCapSlpPresent();
	BOOL GetCapSlpRight90();
	BOOL GetCapSlpRotate180();
	BOOL GetCapSlpUnderline();
	long GetCharacterSet();
	void SetCharacterSet(long nNewValue);
	CString GetCharacterSetList();
	BOOL GetCoverOpen();
	long GetErrorStation();
	BOOL GetFlagWhenIdle();
	void SetFlagWhenIdle(BOOL bNewValue);
	BOOL GetJrnEmpty();
	BOOL GetJrnLetterQuality();
	void SetJrnLetterQuality(BOOL bNewValue);
	long GetJrnLineChars();
	void SetJrnLineChars(long nNewValue);
	CString GetJrnLineCharsList();
	long GetJrnLineHeight();
	void SetJrnLineHeight(long nNewValue);
	long GetJrnLineSpacing();
	void SetJrnLineSpacing(long nNewValue);
	long GetJrnLineWidth();
	BOOL GetJrnNearEnd();
	long GetMapMode();
	void SetMapMode(long nNewValue);
	BOOL GetRecEmpty();
	BOOL GetRecLetterQuality();
	void SetRecLetterQuality(BOOL bNewValue);
	long GetRecLineChars();
	void SetRecLineChars(long nNewValue);
	CString GetRecLineCharsList();
	long GetRecLineHeight();
	void SetRecLineHeight(long nNewValue);
	long GetRecLineSpacing();
	void SetRecLineSpacing(long nNewValue);
	long GetRecLinesToPaperCut();
	long GetRecLineWidth();
	BOOL GetRecNearEnd();
	long GetRecSidewaysMaxChars();
	long GetRecSidewaysMaxLines();
	BOOL GetSlpEmpty();
	BOOL GetSlpLetterQuality();
	void SetSlpLetterQuality(BOOL bNewValue);
	long GetSlpLineChars();
	void SetSlpLineChars(long nNewValue);
	CString GetSlpLineCharsList();
	long GetSlpLineHeight();
	void SetSlpLineHeight(long nNewValue);
	long GetSlpLinesNearEndToEnd();
	long GetSlpLineSpacing();
	void SetSlpLineSpacing(long nNewValue);
	long GetSlpLineWidth();
	long GetSlpMaxLines();
	BOOL GetSlpNearEnd();
	long GetSlpSidewaysMaxChars();
	long GetSlpSidewaysMaxLines();
	long BeginInsertion(long Timeout);
	long BeginRemoval(long Timeout);
	long CutPaper(long Percentage);
	long EndInsertion();
	long EndRemoval();
	long PrintBarCode(long Station, LPCTSTR Data, long Symbology, long Height, long Width, long Alignment, long TextPosition);
	long PrintBitmap(long Station, LPCTSTR FileName, long Width, long Alignment);
	long PrintImmediate(long Station, LPCTSTR Data);
	long PrintNormal(long Station, LPCTSTR Data);
	long PrintTwoNormal(long Stations, LPCTSTR Data1, LPCTSTR Data2);
	long RotatePrint(long Station, long Rotation);
	long SetBitmap(long BitmapNumber, long Station, LPCTSTR FileName, long Width, long Alignment);
	long SetLogo(long Location, LPCTSTR Data);
	long GetCapCharacterSet();
	BOOL GetCapTransaction();
	long GetErrorLevel();
	CString GetErrorString();
	CString GetFontTypefaceList();
	CString GetRecBarCodeRotationList();
	long GetRotateSpecial();
	void SetRotateSpecial(long nNewValue);
	CString GetSlpBarCodeRotationList();
	long TransactionPrint(long Station, long Control);
	long ValidateData(long Station, LPCTSTR Data);
	long GetBinaryConversion();
	void SetBinaryConversion(long nNewValue);
	long GetCapPowerReporting();
	long GetPowerNotify();
	void SetPowerNotify(long nNewValue);
	long GetPowerState();
	long GetCapJrnCartridgeSensor();
	long GetCapJrnColor();
	long GetCapRecCartridgeSensor();
	long GetCapRecColor();
	long GetCapRecMarkFeed();
	BOOL GetCapSlpBothSidesPrint();
	long GetCapSlpCartridgeSensor();
	long GetCapSlpColor();
	long GetCartridgeNotify();
	void SetCartridgeNotify(long nNewValue);
	long GetJrnCartridgeState();
	long GetJrnCurrentCartridge();
	void SetJrnCurrentCartridge(long nNewValue);
	long GetRecCartridgeState();
	long GetRecCurrentCartridge();
	void SetRecCurrentCartridge(long nNewValue);
	long GetSlpCartridgeState();
	long GetSlpCurrentCartridge();
	void SetSlpCurrentCartridge(long nNewValue);
	long GetSlpPrintSide();
	long ChangePrintSide(long Side);
	long MarkFeed(long Type);
	BOOL GetCapMapCharacterSet();
	BOOL GetMapCharacterSet();
	void SetMapCharacterSet(BOOL bNewValue);
	CString GetRecBitmapRotationList();
	CString GetSlpBitmapRotationList();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_OPOSPOSPRINTER_H__DB1EEE5B_68C7_4D5C_A20E_ABCF662AC4EA__INCLUDED_)
