/*
*---------------------------------------------------------------------------
*  Georgia Southern University, Rsearch Services and Sponsored Programs
*    (C) Copyright 2002 - 2020
*
*  NHPOS, donated by NCR Corp to Georgia Southern University, August, 2002.
*  Developemnt with NCR 7448 then ported to Windows XP and generic x86 hardware
*  along with touch screen support.
*
*---------------------------------------------------------------------------
****************************************************************************
**                                                                        **
**        *=*=*=*=*=*=*=*=*                                               **
**        *  NCR 2170     *             AT&T GIS Corporation, E&M OISO    **
**     @  *=*=*=*=*=*=*=*=*  0             (C) Copyright, 1999-2000       **
**    <|\/~               ~\/|>                                           **
**   _/^\_                 _/^\_                                          **
**                                                                        **
****************************************************************************
*===========================================================================
* Title       : Print module Include file used in printer(RJ) module
* Category    : Print, NCR 2170 US Hospitarity Application
* Program Name: PrtRJ.H
* --------------------------------------------------------------------------
* Abstract:
*
* --------------------------------------------------------------------------
* Update Histories
*  Date     : Ver.Rev. :   Name     : Description
*
** NCR2172 **
*
* Jan-07-00 : 01.00.00 : H.Endo     : 
*===========================================================================
*===========================================================================
* PVCS Entry
* --------------------------------------------------------------------------
* $Revision$
* $Date$
* $Author$
* $Log$
*===========================================================================
*/

// The following define test influences the compiling of the
// printer library. There are two types of printers
// that were supported by NHPOS now GenPOS back in the
// days of the NCR 2170 point of sale terminal.
//  - Receipt/Journal printer which had a printed journal (PRINTER_RJ)
//  - Receipt printer only which had an electronic journal (PRINTER_THERMAL)
// These defines are specified on the compiler command line so that
// they are defined with a compiler option on the command line and not
// through a preprocessor directive in a source file.
//   Richard Chambers, Nov-10-2020

#ifdef PRINTER_RJ
#ifndef PRTRJ_H_HEADER_INCLUDE
#define PRTRJ_H_HEADER_INCLUDE

#define  aszCasWaiID                        RJaszCasWaiID
#define  aszEtkCode                         RJaszEtkCode
#define  aszEtkEmp                          RJaszEtkEmp
#define  aszItemAmt                         RJaszItemAmt
#define  aszPrtAM                           RJaszPrtAM
#define  aszPrtAmount                       RJaszPrtAmount
#define  aszPrtAmtMnemShift                 RJaszPrtAmtMnemShift
#define  aszPrtCur                          RJaszPrtCur
#define  aszPrtDate                         RJaszPrtDate
#define  aszPrtDay                          RJaszPrtDay
#define  aszPrtDflHeader                    RJaszPrtDflHeader
#define  aszPrtDflPLUNo                     RJaszPrtDflPLUNo
#define  aszPrtEJAmtDiscMnem                RJaszPrtEJAmtDiscMnem
#define  aszPrtEJAmtMnem                    RJaszPrtEJAmtMnem
#define  aszPrtEJChild                      RJaszPrtEJChild
#define  aszPrtEJChild2                     RJaszPrtEJChild2
#define  aszPrtEJModLinkPLU1                RJaszPrtEJLinkPLU1
#define  aszPrtEJModLinkPLU2                RJaszPrtEJLinkPLU2
#define  aszPrtEJLinkPLU1                   RJaszPrtEJLinkPLU1
#define  aszPrtEJLinkPLU2                   RJaszPrtEJLinkPLU2
#define  aszPrtEJCPFuncErrCode              RJaszPrtEJCPFuncErrCode
#define  aszPrtEJCPRoomCharge               RJaszPrtEJCPRoomCharge
#define  aszPrtEJCPRspMsgText               RJaszPrtEJCPRspMsgText
#define  aszPrtEJCustomerName               RJaszPrtEJCustomerName
#define  aszPrtEJEPTError                   RJaszPrtEJEPTError
#define  aszPrtEJETKCode                    RJaszPrtEJETKCode
#define  aszPrtEJFolioPost                  RJaszPrtEJFolioPost
#define  aszPrtEJForeign1                   RJaszPrtEJForeign1
#define  aszPrtEJForeign2                   RJaszPrtEJForeign2
#define  aszPrtEJGuest_WOCD                 RJaszPrtEJGuest_WOCD
#define  aszPrtEJGuest_WTCD                 RJaszPrtEJGuest_WTCD
#define  aszPrtEJMnemCount                  RJaszPrtEJMnemCount
#define  aszPrtEJMnemMnem                   RJaszPrtEJMnemMnem
#define  aszPrtEJMnemNum                    RJaszPrtEJMnemNum
#define  aszPrtEJModAmtMnem                 RJaszPrtEJModAmtMnem
#define  aszPrtEJMultiSeat                  RJaszPrtEJMultiSeat
#define  aszPrtEJOffDate                    RJaszPrtEJOffDate
#define  aszPrtEJOffline                    RJaszPrtEJOffline
#define  aszPrtEJPerson                     RJaszPrtEJPerson
#define  aszPrtEJPluBuild                   RJaszPrtEJPluBuild
#define  aszPrtEJPPIQuant                   RJaszPrtEJPPIQuant
#define  aszPrtEJPrinNo                     RJaszPrtEJPrinNo
#define  aszPrtEJQuant                      RJaszPrtEJQuant
#define  aszPrtEJResetLog                   RJaszPrtEJResetLog
#define  aszPrtEJResetLog2                  RJaszPrtEJResetLog2
#define  aszPrtEJResetLog3                  RJaszPrtEJResetLog3
#define  aszPrtEJResetLog4                  RJaszPrtEJResetLog4
#define  aszPrtEJResetLog5                  RJaszPrtEJResetLog5
#define  aszPrtEJResetLog6                  RJaszPrtEJResetLog6
#define  aszPrtEJSeat                       RJaszPrtEJSeat
#define  aszPrtEJTblPerson                  RJaszPrtEJTblPerson
#define  aszPrtEJTrail1                     RJaszPrtEJTrail1
#define  aszPrtEJTrail2                     RJaszPrtEJTrail2
#define  aszPrtEJTransNo                    RJaszPrtEJTransNo
#define  aszPrtEJWaiTaxMod                  RJaszPrtEJWaiTaxMod
#define  aszPrtEJWaiter                     RJaszPrtEJWaiter
#define  aszPrtEJWeight1                    RJaszPrtEJWeight1
#define  aszPrtEJWeight2                    RJaszPrtEJWeight2
#define  aszPrtErr                          RJaszPrtErr
#define  aszPrtETKCode                      RJaszPrtETKCode
#define  aszPrtFor                          RJaszPrtFor
#define  aszPrtIssue                        RJaszPrtIssue
#define  aszPrtJFolioPost                   RJaszPrtJFolioPost
#define  aszPrtJPluBuild                    RJaszPrtJPluBuild
#define  aszPrtKP1Space                     RJaszPrtKP1Space
#define  aszPrtKPCustName                   RJaszPrtKPCustName
#define  aszPrtKPGuest                      RJaszPrtKPGuest
#define  aszPrtKPGuest_CD                   RJaszPrtKPGuest_CD
#define  aszPrtKPHeader                     RJaszPrtKPHeader
#define  aszPrtKPOperator                   RJaszPrtKPOperator
#define  aszPrtKPOperator2                  RJaszPrtKPOperator2
#define  aszPrtKPQuant                      RJaszPrtKPQuant
#define  aszPrtKPSeat                       RJaszPrtKPSeat
#define  aszPrtKPTotal                      RJaszPrtKPTotal
#define  aszPrtKPTrailer                    RJaszPrtKPTrailer
#define  aszPrtKPWeight                     RJaszPrtKPWeight
#define  aszPrtNull                         RJaszPrtNull
#define  aszPrtPM                           RJaszPrtPM
#define  aszPrtPTD                          RJaszPrtPTD
#define  aszPrtQty                          RJaszPrtQty
#define  aszPrtRate                         RJaszPrtRate
#define  aszPrtRead                         RJaszPrtRead
#define  aszPrtReset                        RJaszPrtReset
#define  aszPrtRJAmtDiscMnem                RJaszPrtRJAmtDiscMnem
#define  aszPrtRJAmtMnem                    RJaszPrtRJAmtMnem
#define  aszPrtRJChild                      RJaszPrtRJChild
#define  aszPrtRJChild2                     RJaszPrtRJChild2
#define  aszPrtRJLink                       RJaszPrtRJLink
#define  aszPrtRJLink2                      RJaszPrtRJLink2
#define  aszPrtRJCPFuncErrCode              RJaszPrtRJCPFuncErrCode
#define  aszPrtRJCPRoomCharge               RJaszPrtRJCPRoomCharge
#define  aszPrtRJCPRspMsgText               RJaszPrtRJCPRspMsgText
#define  aszPrtRJCustomerName               RJaszPrtRJCustomerName
#define  aszPrtRJDecQty                     RJaszPrtRJDecQty
#define  aszPrtRJDecQtyFor                  RJaszPrtRJDecQtyFor
#define  aszPrtRJEPTError                   RJaszPrtRJEPTError
#define  aszPrtRJEtkCode1                   RJaszPrtRJEtkCode1
#define  aszPrtRJEtkCode2                   RJaszPrtRJEtkCode2
#define  aszPrtRJEuro1                      RJaszPrtRJEuro1
#define  aszPrtRJEuroAmtMnem                RJaszPrtRJEuroAmtMnem
#define  aszPrtRJForeign1                   RJaszPrtRJForeign1
#define  aszPrtRJForeign2                   RJaszPrtRJForeign2
#define  aszPrtRJGuest_WOCD                 RJaszPrtRJGuest_WOCD
#define  aszPrtRJGuest_WTCD                 RJaszPrtRJGuest_WTCD
#define  aszPrtRJMnemCount                  RJaszPrtRJMnemCount
#define  aszPrtRJMnemMnem                   RJaszPrtRJMnemMnem
#define  aszPrtRJMnemNum                    RJaszPrtRJMnemNum
#define  aszPrtRJModAmtMnem                 RJaszPrtRJModAmtMnem
#define  aszPrtRJModScale                   RJaszPrtRJModScale
#define  aszPrtRJMultiSeat                  RJaszPrtRJMultiSeat
#define  aszPrtRJOffDate                    RJaszPrtRJOffDate
#define  aszPrtRJOffline                    RJaszPrtRJOffline
#define  aszPrtRJPerson                     RJaszPrtRJPerson
#define  aszPrtRJPPIQuant                   RJaszPrtRJPPIQuant
#define  aszPrtRJPrinNo                     RJaszPrtRJPrinNo
#define  aszPrtRJQty                        RJaszPrtRJQty
#define  aszPrtRJQtyFor                     RJaszPrtRJQtyFor
#define  aszPrtRJQuant                      RJaszPrtRJQuant
#define  aszPrtRJResetLog                   RJaszPrtRJResetLog
#define  aszPrtRJResetLog2                  RJaszPrtRJResetLog2
#define  aszPrtRJResetLog3                  RJaszPrtRJResetLog3
#define  aszPrtRJResetLog4                  RJaszPrtRJResetLog4
#define  aszPrtRJResetLog5                  RJaszPrtRJResetLog5
#define  aszPrtRJResetLog6                  RJaszPrtRJResetLog6
#define  aszPrtRJSeat                       RJaszPrtRJSeat
#define  aszPrtRJSpecialQty                 RJaszPrtRJSpecialQty
#define  aszPrtRJTblPerson                  RJaszPrtRJTblPerson
#define  aszPrtRJTickTrail_21               RJaszPrtRJTickTrail_21
#define  aszPrtRJTickTrail_24               RJaszPrtRJTickTrail_24
#define  aszPrtRJTrail1_21                  RJaszPrtRJTrail1_21
#define  aszPrtRJTrail1_24                  RJaszPrtRJTrail1_24
#define  aszPrtRJTrail2                     RJaszPrtRJTrail2
#define  aszPrtRJTransNo                    RJaszPrtRJTransNo
#define  aszPrtRJUnitPrice                  RJaszPrtRJUnitPrice
#define  aszPrtRJWaiTaxMod                  RJaszPrtRJWaiTaxMod
#define  aszPrtRJWaiter                     RJaszPrtRJWaiter
#define  aszPrtRJWeight1                    RJaszPrtRJWeight1
#define  aszPrtRJWeight2                    RJaszPrtRJWeight2
#define  aszPrtSave                         RJaszPrtSave
#define  aszPrtSPCancel                     RJaszPrtSPCancel
#define  aszPrtSPChgTps                     RJaszPrtSPChgTps
#define  aszPrtSPChgTpsRate                 RJaszPrtSPChgTpsRate
#define  aszPrtSPChildPLU                   RJaszPrtSPChildPLU
#define  aszPrtSPModLinkPLU1                RJaszPrtSPModLinkPLU1
#define  aszPrtSPModLinkPLU2                RJaszPrtSPModLinkPLU2
#define  aszPrtSPLinkPLU1                   RJaszPrtSPLinkPLU1
#define  aszPrtSPLinkPLU2                   RJaszPrtSPLinkPLU2
#define  aszPrtSPChkPaid                    RJaszPrtSPChkPaid
#define  aszPrtSPCPRoomCharge               RJaszPrtSPCPRoomCharge
#define  aszPrtSPCPRspMsgText               RJaszPrtSPCPRspMsgText
#define  aszPrtSPCustomerName               RJaszPrtSPCustomerName
#define  aszPrtSPDecQty                     RJaszPrtSPDecQty
#define  aszPrtSPDecQtyFor                  RJaszPrtSPDecQtyFor
#define  aszPrtSPDiscount                   RJaszPrtSPDiscount
#define  aszPrtSPEtkTimeIn                  RJaszPrtSPEtkTimeIn
#define  aszPrtSPEtkTimeOut                 RJaszPrtSPEtkTimeOut
#define  aszPrtSPForeign1                   RJaszPrtSPForeign1
#define  aszPrtSPForeign2                   RJaszPrtSPForeign2
#define  aszPrtSPGCNo                       RJaszPrtSPGCNo
#define  aszPrtSPGCNoCdv                    RJaszPrtSPGCNoCdv
#define  aszPrtSPGCTran                     RJaszPrtSPGCTran
#define  aszPrtSPGCTranCdv                  RJaszPrtSPGCTranCdv
#define  aszPrtSPGCTrnTril                  RJaszPrtSPGCTrnTril
#define  aszPrtSPHdr1                       RJaszPrtSPHdr1
#define  aszPrtSPHdr1Cdv                    RJaszPrtSPHdr1Cdv
#define  aszPrtSPHdrTrans                   RJaszPrtSPHdrTrans
#define  aszPrtSPHead1                      RJaszPrtSPHead1
#define  aszPrtSPHead2                      RJaszPrtSPHead2
#define  aszPrtSPHeader2nd                  RJaszPrtSPHeader2nd
#define  aszPrtSPItemAmt                    RJaszPrtSPItemAmt
#define  aszPrtSPMnem                       RJaszPrtSPMnem
#define  aszPrtSPMnemAmt                    RJaszPrtSPMnemAmt
#define  aszPrtSPMnemAmtD                   RJaszPrtSPMnemAmtD
#define  aszPrtSPMnemMnem                   RJaszPrtSPMnemMnem
#define  aszPrtSPMnemNatAmtD                RJaszPrtSPMnemNatAmtD
#define  aszPrtSPMnemNatAmtS                RJaszPrtSPMnemNatAmtS
#define  aszPrtSPMnemTax                    RJaszPrtSPMnemTax
#define  aszPrtSPMnemTaxAmt                 RJaszPrtSPMnemTaxAmt
#define  aszPrtSPMnemTaxQty                 RJaszPrtSPMnemTaxQty
#define  aszPrtSPMnlWeight1                 RJaszPrtSPMnlWeight1
#define  aszPrtSPMnlWeight2                 RJaszPrtSPMnlWeight2
#define  aszPrtSPMnlWeight3                 RJaszPrtSPMnlWeight3
#define  aszPrtSPMoneyForeign               RJaszPrtSPMoneyForeign
#define  aszPrtSPMultiSeat                  RJaszPrtSPMultiSeat
#define  aszPrtSPNext                       RJaszPrtSPNext
#define  aszPrtSPOffDate                    RJaszPrtSPOffDate
#define  aszPrtSPOffline                    RJaszPrtSPOffline
#define  aszPrtSPPluBuild                   RJaszPrtSPPluBuild
#define  aszPrtSPPLUNo                      RJaszPrtSPPLUNo
#define  aszPrtSPPPIQty                     RJaszPrtSPPPIQty
#define  aszPrtSPQty                        RJaszPrtSPQty
#define  aszPrtSPQtyFor                     RJaszPrtSPQtyFor
#define  aszPrtSPScale                      RJaszPrtSPScale
#define  aszPrtSPSeat                       RJaszPrtSPSeat
#define  aszPrtSPServTotal1                 RJaszPrtSPServTotal1
#define  aszPrtSPServTotal2                 RJaszPrtSPServTotal2
#define  aszPrtSPSevTaxSum                  RJaszPrtSPSevTaxSum
#define  aszPrtSPSevTaxSumS                 RJaszPrtSPSevTaxSumS
#define  aszPrtSPTaxAmt                     RJaszPrtSPTaxAmt
#define  aszPrtSPTaxDisc                    RJaszPrtSPTaxDisc
#define  aszPrtSPTaxMnem                    RJaszPrtSPTaxMnem
#define  aszPrtSPTaxMod                     RJaszPrtSPTaxMod
#define  aszPrtSPTaxRateAmt                 RJaszPrtSPTaxRateAmt
#define  aszPrtSPTblPerson                  RJaszPrtSPTblPerson
#define  aszPrtSPTipsPO                     RJaszPrtSPTipsPO
#define  aszPrtSPTrail1                     RJaszPrtSPTrail1
#define  aszPrtSPTrail2                     RJaszPrtSPTrail2
#define  aszPrtSPTranMnem                   RJaszPrtSPTranMnem
#define  aszPrtSPTranNumber                 RJaszPrtSPTranNumber
#define  aszPrtSPTransPerson                RJaszPrtSPTransPerson
#define  aszPrtSPTrayCo                     RJaszPrtSPTrayCo
#define  aszPrtSPVLHead                     RJaszPrtSPVLHead
#define  aszPrtSPWeight1                    RJaszPrtSPWeight1
#define  aszPrtSPWeight2                    RJaszPrtSPWeight2
#define  aszPrtSupSPHead                    RJaszPrtSupSPHead
#define  aszPrtSupSPTrail1                  RJaszPrtSupSPTrail1
#define  aszPrtSupSPTrail2                  RJaszPrtSupSPTrail2
#define  aszPrtSupVLFor                     RJaszPrtSupVLFor
#define  aszPrtSupVLForeign                 RJaszPrtSupVLForeign
#define  aszPrtSupVLForeignTend             RJaszPrtSupVLForeignTend
#define  aszPrtSupVLHead                    RJaszPrtSupVLHead
#define  aszPrtSupVLQty                     RJaszPrtSupVLQty
#define  aszPrtSupVLTrail                   RJaszPrtSupVLTrail
#define  aszPrtTHAmtDiscMnem                RJaszPrtTHAmtDiscMnem
#define  aszPrtTHAmtMnem                    RJaszPrtTHAmtMnem
#define  aszPrtTHAmtMnemMnem                RJaszPrtTHAmtMnemMnem
#define  aszPrtTHAmtMnemSpace               RJaszPrtTHAmtMnemSpace
#define  aszPrtTHAmtS                       RJaszPrtTHAmtS
#define  aszPrtTHAmtTaxMnem                 RJaszPrtTHAmtTaxMnem
#define  aszPrtTHCasOrdr                    RJaszPrtTHCasOrdr
#define  aszPrtTHChild                      RJaszPrtTHChild
#define  aszPrtTHModLinkPLU                 RJaszPrtTHModLinkPLU
#define  aszPrtTHLinkPLU                    RJaszPrtTHLinkPLU
#define  aszPrtTHCPRoomCharge               RJaszPrtTHCPRoomCharge
#define  aszPrtTHCPRspMsgText               RJaszPrtTHCPRspMsgText
#define  aszPrtTHCustomerName               RJaszPrtTHCustomerName
#define  aszPrtTHDecQty                     RJaszPrtTHDecQty
#define  aszPrtTHDecQtyFor                  RJaszPrtTHDecQtyFor
#define  aszPrtTHEPTError                   RJaszPrtTHEPTError
#define  aszPrtTHEuro1                      RJaszPrtTHEuro1
#define  aszPrtTHEuroAmtMnem                RJaszPrtTHEuroAmtMnem
#define  aszPrtTHForeign                    RJaszPrtTHForeign
#define  aszPrtTHGC_WOCD_S                  RJaszPrtTHGC_WOCD_S
#define  aszPrtTHGC_WTCD_S                  RJaszPrtTHGC_WTCD_S
#define  aszPrtTHGuest_D                    RJaszPrtTHGuest_D
#define  aszPrtTHMnemCount                  RJaszPrtTHMnemCount
#define  aszPrtTHMnemMnem                   RJaszPrtTHMnemMnem
#define  aszPrtTHMnemNum                    RJaszPrtTHMnemNum
#define  aszPrtTHMoneyForeign               RJaszPrtTHMoneyForeign
#define  aszPrtTHMultiSeat                  RJaszPrtTHMultiSeat
#define  aszPrtTHOffDate                    RJaszPrtTHOffDate
#define  aszPrtTHOffline                    RJaszPrtTHOffline
#define  aszPrtTHPPIQuant                   RJaszPrtTHPPIQuant
#define  aszPrtTHPrinNo                     RJaszPrtTHPrinNo
#define  aszPrtTHQty                        RJaszPrtTHQty
#define  aszPrtTHQuant                      RJaszPrtTHQuant
#define  aszPrtTHSeat                       RJaszPrtTHSeat
#define  aszPrtTHTaxRateAmt                 RJaszPrtTHTaxRateAmt
#define  aszPrtTHTblPerGC                   RJaszPrtTHTblPerGC
#define  aszPrtTHTblPerson                  RJaszPrtTHTblPerson
#define  aszPrtTHTickTrail1                 RJaszPrtTHTickTrail1
#define  aszPrtTHTickTrail2                 RJaszPrtTHTickTrail2
#define  aszPrtTHTrail1                     RJaszPrtTHTrail1
#define  aszPrtTHTrail2                     RJaszPrtTHTrail2
#define  aszPrtTHTransNo                    RJaszPrtTHTransNo
#define  aszPrtTHTransPerson                RJaszPrtTHTransPerson
#define  aszPrtTHVatAmt                     RJaszPrtTHVatAmt
#define  aszPrtTHVatMnem                    RJaszPrtTHVatMnem
#define  aszPrtTHWaiAmtMnem                 RJaszPrtTHWaiAmtMnem
#define  aszPrtTHWaiGC_WOCD                 RJaszPrtTHWaiGC_WOCD
#define  aszPrtTHWaiGC_WTCD                 RJaszPrtTHWaiGC_WTCD
#define  aszPrtTHWaiTaxMod                  RJaszPrtTHWaiTaxMod
#define  aszPrtTHWeight1                    RJaszPrtTHWeight1
#define  aszPrtTHWeight2                    RJaszPrtTHWeight2
#define  aszPrtTime                         RJaszPrtTime
#define  aszPrtTimeWithZone                 RJaszPrtTimeWithZone
#define  aszPrtTrayCount                    RJaszPrtTrayCount
#define  aszPrtVLAccNum                     RJaszPrtVLAccNum
#define  aszPrtVLAmtMnem                    RJaszPrtVLAmtMnem
#define  aszPrtVLAmtPerMnem                 RJaszPrtVLAmtPerMnem
#define  aszPrtVLAmtPerMnem2                RJaszPrtVLAmtPerMnem2
#define  aszPrtVLAmtTmp                     RJaszPrtVLAmtTmp
#define  aszPrtVLChgTip                     RJaszPrtVLChgTip
#define  aszPrtVLCoupon                     RJaszPrtVLCoupon
#define  aszPrtVLDoubleMnemAmt              RJaszPrtVLDoubleMnemAmt
#define  aszPrtVLEtkTimeIn                  RJaszPrtVLEtkTimeIn
#define  aszPrtVLEtkTimeOut                 RJaszPrtVLEtkTimeOut
#define  aszPrtVLForeign                    RJaszPrtVLForeign
#define  aszPrtVLForeignTend                RJaszPrtVLForeignTend
#define  aszPrtVLHead                       RJaszPrtVLHead
#define  aszPrtVLMnemAmt                    RJaszPrtVLMnemAmt
#define  aszPrtVLNumber                     RJaszPrtVLNumber
#define  aszPrtVLNumberCP                   RJaszPrtVLNumberCP
#define  aszPrtVLNumPPIQuant                RJaszPrtVLNumPPIQuant
#define  aszPrtVLNumQuant                   RJaszPrtVLNumQuant
#define  aszPrtVLNumWeight                  RJaszPrtVLNumWeight
#define  aszPrtVLOffDate                    RJaszPrtVLOffDate
#define  aszPrtVLOffDateTtl                 RJaszPrtVLOffDateTtl
#define  aszPrtVLOffline                    RJaszPrtVLOffline
#define  aszPrtVLProduct                    RJaszPrtVLProduct
#define  aszPrtVLProduct2                   RJaszPrtVLProduct2
#define  aszPrtVLTender1                    RJaszPrtVLTender1
#define  aszPrtVLTender2                    RJaszPrtVLTender2
#define  aszPrtVLTipPO                      RJaszPrtVLTipPO
#define  aszPrtVLTotal                      RJaszPrtVLTotal
#define  aszPrtVLTrail                      RJaszPrtVLTrail
#define  aszPrtVLTray                       RJaszPrtVLTray
#define  aszPrtVLPluBuild                   RJaszPrtVLPluBuild
#define  aszPrtVSAmtIDMnem                  RJaszPrtVSAmtIDMnem
#define  aszPrtVSAmtMnem                    RJaszPrtVSAmtMnem
#define  aszPrtVSAmtPerMnem                 RJaszPrtVSAmtPerMnem
#define  aszPrtVSForeign                    RJaszPrtVSForeign
#define  aszPrtVSMDC1                       RJaszPrtVSMDC1
#define  aszPrtVSMDC2                       RJaszPrtVSMDC2
#define  aszPrtVSMDC3                       RJaszPrtVSMDC3
#define  aszPrtVSModeSym                    RJaszPrtVSModeSym
#define  aszPrtVSTotal                      RJaszPrtVSTotal
#define  aszPrtWaiter                       RJaszPrtWaiter
#define  aszPrtRJAmtMnemSI                  RJaszPrtRJAmtMnemSI
#define  aszPrtRJAmtDiscMnemSI              RJaszPrtRJAmtDiscMnemSI
#define  auchAMPM                           RJauchAMPM
#define  auchDate                           RJauchDate
#define  auchEtkAMPM                        RJauchEtkAMPM
#define  auchEtkDate                        RJauchEtkDate
#define  auchEtkTime                        RJauchEtkTime
#define  auchPrtNoPrintPLUHigh              RJauchPrtNoPrintPLUHigh
#define  auchPrtNoPrintPLULow               RJauchPrtNoPrintPLULow
#define  auchPrtSupEJTOD1                   RJauchPrtSupEJTOD1
#define  auchPrtSupEJTOD2                   RJauchPrtSupEJTOD2
#define  auchPrtSupRJTOD1                   RJauchPrtSupRJTOD1
#define  auchPrtSupRJTOD2                   RJauchPrtSupRJTOD2
#define  auchPrtSupTHTOD1                   RJauchPrtSupTHTOD1
#define  auchPrtSupTHTOD2                   RJauchPrtSupTHTOD2
#define  auchPrtSupTrailer1                 RJauchPrtSupTrailer1
#define  auchPrtSupTrailer2                 RJauchPrtSupTrailer2
#define  auchPrtSupTrailer3                 RJauchPrtSupTrailer3
#define  auchPrtSupTrailer4                 RJauchPrtSupTrailer4
#define  auchPrtSupTrailer5                 RJauchPrtSupTrailer5
#define  auchPrtThrmSupTrailer1             RJauchPrtThrmSupTrailer1
#define  auchPrtThrmSupTrailer2             RJauchPrtThrmSupTrailer2
#define  auchPrtThrmSupTrailer3             RJauchPrtThrmSupTrailer3
#define  auchPrtThrmSupTrailer4             RJauchPrtThrmSupTrailer4
#define  auchThrmEtkAMPM                    RJauchThrmEtkAMPM
#define  auchThrmEtkDate                    RJauchThrmEtkDate
#define  auchThrmEtkTime                    RJauchThrmEtkTime
#define  auchTime                           RJauchTime
#define  auchTimeWage                       RJauchTimeWage
#define  PrtAddChk1                         RJPrtAddChk1
#define  PrtAddChk1_EJ                      RJPrtAddChk1_EJ
#define  PrtAddChk1_RJ                      RJPrtAddChk1_RJ
#define  PrtAddChk1_SP                      RJPrtAddChk1_SP
#define  PrtAddChk1_TH                      RJPrtAddChk1_TH
#define  PrtAddChk2                         RJPrtAddChk2
#define  PrtAddChk2_EJ                      RJPrtAddChk2_EJ
#define  PrtAddChk2_RJ                      RJPrtAddChk2_RJ
#define  PrtAddChk2_SP                      RJPrtAddChk2_SP
#define  PrtAddChk2_TH                      RJPrtAddChk2_TH
#define  PrtAdjustForeign                   RJPrtAdjustForeign
#define  PrtAdjustNative                    RJPrtAdjustNative
#define  PrtAdjustString                    RJPrtAdjustString
#define  PrtAgeLog                          RJPrtAgeLog
#define  PrtAgeLog_EJ                       RJPrtAgeLog_EJ
#define  PrtAgeLog_J                        RJPrtAgeLog_J
#define  PrtAltrMsg                         RJPrtAltrMsg
#define  PrtCallIPD                         RJPrtCallIPD
#define  PrtCanadaTax                       RJPrtCanadaTax
#define  PrtCanAll                          RJPrtCanAll
#define  PrtCanAll_EJ                       RJPrtCanAll_EJ
#define  PrtCanAll_RJ                       RJPrtCanAll_RJ
#define  PrtCanAll_SP                       RJPrtCanAll_SP
#define  PrtCanAll_TH                       RJPrtCanAll_TH
#define  PrtCancel                          RJPrtCancel
#define  PrtCancel_EJ                       RJPrtCancel_EJ
#define  PrtCancel_RJ                       RJPrtCancel_RJ
#define  PrtCancel_SP                       RJPrtCancel_SP
#define  PrtCancel_TH                       RJPrtCancel_TH
#define  PrtCanGst                          RJPrtCanGst
#define  PrtCanGst_EJ                       RJPrtCanGst_EJ
#define  PrtCanGst_RJ                       RJPrtCanGst_RJ
#define  PrtCanGst_SP                       RJPrtCanGst_SP
#define  PrtCanGst_TH                       RJPrtCanGst_TH
#define  PrtCanInd                          RJPrtCanInd
#define  PrtCanInd_EJ                       RJPrtCanInd_EJ
#define  PrtCanInd_RJ                       RJPrtCanInd_RJ
#define  PrtCanInd_SP                       RJPrtCanInd_SP
#define  PrtCanInd_TH                       RJPrtCanInd_TH
#define  PrtCasIn                           RJPrtCasIn
#define  PrtCasIn_EJ                        RJPrtCasIn_EJ
#define  PrtCasIn_RJ                        RJPrtCasIn_RJ
#define  PrtCasIn_SP                        RJPrtCasIn_SP
#define  PrtCasIn_TH                        RJPrtCasIn_TH
#define  PrtChangeFont                      RJPrtChangeFont
#define  PrtCheckAbort                      RJPrtCheckAbort
#define  PrtCheckLine                       RJPrtCheckLine
#define  PrtCheckShr                        RJPrtCheckShr
#define  PrtCheckTenderMedia                RJPrtCheckTenderMedia
#define  PrtCheckTran                       RJPrtCheckTran
#define  PrtCheckTran_EJ                    RJPrtCheckTran_EJ
#define  PrtCheckTran_RJ                    RJPrtCheckTran_RJ
#define  PrtCheckTran_SP                    RJPrtCheckTran_SP
#define  PrtCheckTran_TH                    RJPrtCheckTran_TH
#define  PrtChkCasWai                       RJPrtChkCasWai
#define  PrtChkCurSlip                      RJPrtChkCurSlip
#define  PrtChkDiscAdr                      RJPrtChkDiscAdr
#define  PrtChkFrame                        RJPrtChkFrame
#define  PrtChkFullSP                       RJPrtChkFullSP
#define  PrtChkKPItem                       RJPrtChkKPItem
#define  PrtChkKPPort                       RJPrtChkKPPort
#define  PrtChkKPPortSub                    RJPrtChkKPPortSub
#define  PrtChkKPPortSub2                   RJPrtChkKPPortSub2
#define  PrtChkKPStorage                    RJPrtChkKPStorage
#define  PrtChkKPStorageEx                  RJPrtChkKPStorageEx
#define  PrtChkLoanPickupAdr                RJPrtChkLoanPickupAdr
#define  PrtChkPaid                         RJPrtChkPaid
#define  PrtChkPaid_SP                      RJPrtChkPaid_SP
#define  PrtChkPort                         RJPrtChkPort
#define  PrtChkPrintPluNo                   RJPrtChkPrintPluNo
#define  PrtChkPrintType                    RJPrtChkPrintType
#define  PrtChkStorage                      RJPrtChkStorage
#define  PrtChkTendAdr                      RJPrtChkTendAdr
#define  PrtChkTotalKP                      RJPrtChkTotalKP
#define  PrtChkTotalKP2                     RJPrtChkTotalKP2
#define  PrtChkVoidConsolidation            RJPrtChkVoidConsolidation
#define  PrtChrgTip                         RJPrtChrgTip
#define  PrtChrgTip_EJ                      RJPrtChrgTip_EJ
#define  PrtChrgTip_RJ                      RJPrtChrgTip_RJ
#define  PrtChrgTip_SP                      RJPrtChrgTip_SP
#define  PrtChrgTip_TH                      RJPrtChrgTip_TH
#define  PrtChrgTip_VL                      RJPrtChrgTip_VL
#define  PrtChrgTipID                       RJPrtChrgTipID
#define  PrtCoupon                          RJPrtCoupon
#define  PrtCoupon_EJ                       RJPrtCoupon_EJ
#define  PrtCoupon_RJ                       RJPrtCoupon_RJ
#define  PrtCoupon_SP                       RJPrtCoupon_SP
#define  PrtCoupon_TH                       RJPrtCoupon_TH
#define  PrtCoupon_VL                       RJPrtCoupon_VL
#define  PrtCPFuncErrCode_EJ                RJPrtCPFuncErrCode_EJ
#define  PrtCPFuncErrCode_RJ                RJPrtCPFuncErrCode_RJ
#define  PrtCPGusLine                       RJPrtCPGusLine
#define  PrtCPGusLine_RJ                    RJPrtCPGusLine_RJ
#define  PrtCPGusLine_TH                    RJPrtCPGusLine_TH
#define  PrtCPRespText                      RJPrtCPRespText
#define  PrtCPRespText_SP                   RJPrtCPRespText_SP
#define  PrtCut                             RJPrtCut
#define  PrtDept                            RJPrtDept
#define  PrtDeptPLU_EJ                      RJPrtDeptPLU_EJ
#define  PrtDeptPLU_RJ                      RJPrtDeptPLU_RJ
#define  PrtDeptPLU_SP                      RJPrtDeptPLU_SP
#define  PrtDeptPLU_TH                      RJPrtDeptPLU_TH
#define  PrtDeptPLUModDisc_EJ               RJPrtDeptPLUModDisc_EJ
#define  PrtDeptPLUModDisc_RJ               RJPrtDeptPLUModDisc_RJ
#define  PrtDeptPLUModDisc_TH               RJPrtDeptPLUModDisc_TH
#define  PrtDeptPLUSet_VL                   RJPrtDeptPLUSet_VL
#define  PrtDflAddChk2                      RJPrtDflAddChk2
#define  PrtDflAgeLog                       RJPrtDflAgeLog
#define  PrtDflAgeLogForm                   RJPrtDflAgeLogForm
#define  PrtDflAmtMnem                      RJPrtDflAmtMnem
#define  PrtDflAmtMnemShift                 RJPrtDflAmtMnemShift
#define  PrtDflAmtSym                       RJPrtDflAmtSym
#define  PrtDflCanadaTax                    RJPrtDflCanadaTax
#define  PrtDflCanAll                       RJPrtDflCanAll
#define  PrtDflCancel                       RJPrtDflCancel
#define  PrtDflCancelForm                   RJPrtDflCancelForm
#define  PrtDflCanGst                       RJPrtDflCanGst
#define  PrtDflCanInd                       RJPrtDflCanInd
#define  PrtDflCheckTran                    RJPrtDflCheckTran
#define  PrtDflCheckVoid                    RJPrtDflCheckVoid
#define  PrtDflChild                        RJPrtDflChild
#define  PrtDflLinkPLU                      RJPrtDflLinkPLU
#define  PrtDflChrgTip                      RJPrtDflChrgTip
#define  PrtDflChrgTipForm                  RJPrtDflChrgTipForm
#define  PrtDflCoupon                       RJPrtDflCoupon
#define  PrtDflCouponForm                   RJPrtDflCouponForm
#define  PrtDflCpnItem                      RJPrtDflCpnItem
#define  PrtDflCPRoomCharge                 RJPrtDflCPRoomCharge
#define  PrtDflCPRspMsgText                 RJPrtDflCPRspMsgText
#define  PrtDflCustHeader                   RJPrtDflCustHeader
#define  PrtDflCustName                     RJPrtDflCustName
#define  PrtDflDeptPLU                      RJPrtDflDeptPLU
#define  PrtDflDeptPLUForm                  RJPrtDflDeptPLUForm
#define  PrtDflDispNumber                   RJPrtDflDispNumber
#define  PrtDflDispNumberForm               RJPrtDflDispNumberForm
#define  PrtDflFolioPost                    RJPrtDflFolioPost
#define  PrtDflForeign1                     RJPrtDflForeign1
#define  PrtDflForeign2                     RJPrtDflForeign2
#define  PrtDflForeign3                     RJPrtDflForeign3
#define  PrtDflForeignTender                RJPrtDflForeignTender
#define  PrtDflForeignTenderForm            RJPrtDflForeignTenderForm
#define  PrtDflForeignTotal                 RJPrtDflForeignTotal
#define  PrtDflForeignTotalForm             RJPrtDflForeignTotalForm
#define  PrtDflGetNo                        RJPrtDflGetNo
#define  PrtDflGuest                        RJPrtDflGuest
#define  PrtDflHeader                       RJPrtDflHeader
#define  PrtDflInit                         RJPrtDflInit
#define  PrtDflItems                        RJPrtDflItems
#define  PrtDflIType                        RJPrtDflIType
#define  PrtDflMnem                         RJPrtDflMnem
#define  PrtDflMnemCount                    RJPrtDflMnemCount
#define  PrtDflMnemonic                     RJPrtDflMnemonic
#define  PrtDflModCustName                  RJPrtDflModCustName
#define  PrtDflModCustNameForm              RJPrtDflModCustNameForm
#define  PrtDflModDisc                      RJPrtDflModDisc
#define  PrtDflModDiscForm                  RJPrtDflModDiscForm
#define  PrtDflModPerson                    RJPrtDflModPerson
#define  PrtDflModPersonForm                RJPrtDflModPersonForm
#define  PrtDflModTable                     RJPrtDflModTable
#define  PrtDflModTableForm                 RJPrtDflModTableForm
#define  PrtDflModTaxForm                   RJPrtDflModTaxForm
#define  PrtDflMoney                        RJPrtDflMoney
#define  PrtDflMulChk                       RJPrtDflMulChk
#define  PrtDflMulti                        RJPrtDflMulti
#define  PrtDflMultiTotal                   RJPrtDflMultiTotal
#define  PrtDflNoSale                       RJPrtDflNoSale
#define  PrtDflNoSaleForm                   RJPrtDflNoSaleForm
#define  PrtDflNumber                       RJPrtDflNumber
#define  PrtDflMnemNumber                   RJPrtDflMnemNumber
#define  PrtDflOffline                      RJPrtDflOffline
#define  PrtDflOffTend                      RJPrtDflOffTend
#define  PrtDflPaidOut                      RJPrtDflPaidOut
#define  PrtDflPaidOutForm                  RJPrtDflPaidOutForm
#define  PrtDflPerDisc                      RJPrtDflPerDisc
#define  PrtDflPLUNo                        RJPrtDflPLUNo
#define  PrtDflPrtMod                       RJPrtDflPrtMod
#define  PrtDflPrtModForm                   RJPrtDflPrtModForm
#define  PrtDflQty                          RJPrtDflQty
#define  PrtDflLinkQty                      RJPrtDflLinkQty
#define  PrtDflRandomNumber                 RJPrtDflRandomNumber
#define  PrtDflRecvOnAcnt                   RJPrtDflRecvOnAcnt
#define  PrtDflRecvOnAcntForm               RJPrtDflRecvOnAcntForm
#define  PrtDflRegDisc                      RJPrtDflRegDisc
#define  PrtDflRegDiscForm                  RJPrtDflRegDiscForm
#define  PrtDflReorder                      RJPrtDflReorder
#define  PrtDflReorderForm                  RJPrtDflReorderForm
#define  PrtDflSeatNo                       RJPrtDflSeatNo
#define  PrtDflSend                         RJPrtDflSend
#define  PrtDflServTotal                    RJPrtDflServTotal
#define  PrtDflServTotalForm                RJPrtDflServTotalForm
#define  PrtDflServTotalStubPost            RJPrtDflServTotalStubPost
#define  PrtDflServTotalStubPostForm        RJPrtDflServTotalStubPostForm
#define  PrtDflSET                          RJPrtDflSET
#define  PrtDflSETChkChildKP                RJPrtDflSETChkChildKP
#define  PrtDflSetCRTNo                     RJPrtDflSetCRTNo
#define  PrtDflSetData                      RJPrtDflSetData
#define  PrtDflSETForm                      RJPrtDflSETForm
#define  PrtDflSetModDisc                   RJPrtDflSetModDisc
#define  PrtDflSetModDiscForm               RJPrtDflSetModDiscForm
#define  PrtDflSETParent                    RJPrtDflSETParent
#define  PrtDflSETSend                      RJPrtDflSETSend
#define  PrtDflSETSendAsNotKP               RJPrtDflSETSendAsNotKP
#define  PrtDflSETSendNoKPChild             RJPrtDflSETSendNoKPChild
#define  PrtDflSetTtlNo                     RJPrtDflSetTtlNo
#define  PrtDflTax                          RJPrtDflTax
#define  PrtDflTaxForm                      RJPrtDflTaxForm
#define  PrtDflTaxMod                       RJPrtDflTaxMod
#define  PrtDflTaxMod2                      RJPrtDflTaxMod2
#define  PrtDflTblPerson                    RJPrtDflTblPerson
#define  PrtDflTender                       RJPrtDflTender
#define  PrtDflTenderForm                   RJPrtDflTenderForm
#define  PrtDflTipsDecld                    RJPrtDflTipsDecld
#define  PrtDflTipsDecldForm                RJPrtDflTipsDecldForm
#define  PrtDflTipsPaidOut                  RJPrtDflTipsPaidOut
#define  PrtDflTipsPaidOutForm              RJPrtDflTipsPaidOutForm
#define  PrtDflTotal                        RJPrtDflTotal
#define  PrtDflTotalForm                    RJPrtDflTotalForm
#define  PrtDflTrailer                      RJPrtDflTrailer
#define  PrtDflTranNum                      RJPrtDflTranNum
#define  PrtDflTrayTotal                    RJPrtDflTrayTotal
#define  PrtDflTrayTotalForm                RJPrtDflTrayTotalForm
#define  PrtDflTrType                       RJPrtDflTrType
#define  PrtDflUSCanTaxForm                 RJPrtDflUSCanTaxForm
#define  PrtDflUSTax                        RJPrtDflUSTax
#define  PrtDflVAT                          RJPrtDflVAT
#define  PrtDflVATForm                      RJPrtDflVATForm
#define  PrtDflVATServ                      RJPrtDflVATServ
#define  PrtDflVATServForm                  RJPrtDflVATServForm
#define  PrtDflVATSubtotal                  RJPrtDflVATSubtotal
#define  PrtDflVoid                         RJPrtDflVoid
#define  PrtDflWaiTaxMod                    RJPrtDflWaiTaxMod
#define  PrtDflWaiter                       RJPrtDflWaiter
#define  PrtDflWeight                       RJPrtDflWeight
#define  PrtDflXor                          RJPrtDflXor
#define  PrtDflZAMnemShift                  RJPrtDflZAMnemShift
#define  PrtDflZeroAmtMnem                  RJPrtDflZeroAmtMnem
#define  PrtDispAffection                   RJPrtDispAffection
#define  PrtDispAffectionForm               RJPrtDispAffectionForm
#define  PrtDispCoupon                      RJPrtDispCoupon
#define  PrtDispCouponForm                  RJPrtDispCouponForm
#define  PrtDispDisc                        RJPrtDispDisc
#define  PrtDispDiscForm                    RJPrtDispDiscForm
#define  PrtDispItem                        RJPrtDispItem
#define  PrtDispItemForm                    RJPrtDispItemForm
#define  PrtDispMisc                        RJPrtDispMisc
#define  PrtDispMiscForm                    RJPrtDispMiscForm
#define  PrtDispModifier                    RJPrtDispModifier
#define  PrtDispModifierForm                RJPrtDispModifierForm
#define  PrtDispMulti                       RJPrtDispMulti
#define  PrtDispPrint                       RJPrtDispPrint
#define  PrtDispPrintForm                   RJPrtDispPrintForm
#define  PrtDispSales                       RJPrtDispSales
#define  PrtDispSalesForm                   RJPrtDispSalesForm
#define  PrtDispTender                      RJPrtDispTender
#define  PrtDispTenderForm                  RJPrtDispTenderForm
#define  PrtDispTotal                       RJPrtDispTotal
#define  PrtDispTotalForm                   RJPrtDispTotalForm
#define  PrtDispTransOpen                   RJPrtDispTransOpen
#define  PrtDispTransOpenForm               RJPrtDispTransOpenForm
#define  PrtDouble                          RJPrtDouble
#define  PrtDoubleHeader                    RJPrtDoubleHeader
#define  PrtEJAmtMnem                       RJPrtEJAmtMnem
#define  PrtEJAmtMnemShift                  RJPrtEJAmtMnemShift
#define  PrtEJAmtSym                        RJPrtEJAmtSym
#define  PrtEJAmtSymEuro                    RJPrtEJAmtSymEuro
#define  PrtEJChild                         RJPrtEJChild
#define  PrtEJLinkPLU                       RJPrtEJLinkPLU
#define  PrtEJCoupon                        RJPrtEJCoupon
#define  PrtEJCPRoomCharge                  RJPrtEJCPRoomCharge
#define  PrtEJCPRspMsgText                  RJPrtEJCPRspMsgText
#define  PrtEJCustomerName                  RJPrtEJCustomerName
#define  PrtEJDiscItems                     RJPrtEJDiscItems
#define  PrtEJEPTError                      RJPrtEJEPTError
#define  PrtEJEtkCode                       RJPrtEJEtkCode
#define  PrtEJEuro                          RJPrtEJEuro
#define  PrtEJFolioPost                     RJPrtEJFolioPost
#define  PrtEJForeign1                      RJPrtEJForeign1
#define  PrtEJForeign2                      RJPrtEJForeign2
#define  PrtEJGuest                         RJPrtEJGuest
#define  PrtEJInit                          RJPrtEJInit
#define  PrtEJItems                         RJPrtEJItems
#define  PrtEJJobTimeIn                     RJPrtEJJobTimeIn
#define  PrtEJJobTimeOut                    RJPrtEJJobTimeOut
#define  PrtEJMnem                          RJPrtEJMnem
#define  PrtEJMnemCount                     RJPrtEJMnemCount
#define  PrtEJMulChk                        RJPrtEJMulChk
#define  PrtEJMultiSeatNo                   RJPrtEJMultiSeatNo
#define  PrtEJNumber                        RJPrtEJNumber
#define  PrtEJMnemNumber                    RJPrtEJMnemNumber
#define  PrtEJOffline                       RJPrtEJOffline
#define  PrtEJOffTend                       RJPrtEJOffTend
#define  PrtEJPerDisc                       RJPrtEJPerDisc
#define  PrtEJPLUBuild                      RJPrtEJPLUBuild
#define  PrtEJPLUNo                         RJPrtEJPLUNo
#define  PrtEJQty                           RJPrtEJQty
#define  PrtEJLinkQty                       RJPrtEJLinkQty
#define  PrtEJResetLog                      RJPrtEJResetLog
#define  PrtEJResetLog3                     RJPrtEJResetLog3
#define  PrtEJResetLog4                     RJPrtEJResetLog4
#define  PrtEJSeatNo                        RJPrtEJSeatNo
#define  PrtEJSend                          RJPrtEJSend
#define  PrtEJSupFormTrailer                RJPrtEJSupFormTrailer
#define  PrtEJTaxMod                        RJPrtEJTaxMod
#define  PrtEJTblPerson                     RJPrtEJTblPerson
#define  PrtEJTrail1                        RJPrtEJTrail1
#define  PrtEJTrail2                        RJPrtEJTrail2
#define  PrtEJTranNum                       RJPrtEJTranNum
#define  PrtEJVoid                          RJPrtEJVoid
#define  PrtEJWaiTaxMod                     RJPrtEJWaiTaxMod
#define  PrtEJWaiter                        RJPrtEJWaiter
#define  PrtEJWeight                        RJPrtEJWeight
#define  PrtEJWrite                         RJPrtEJWrite
#define  PrtEJZAMnemShift                   RJPrtEJZAMnemShift
#define  PrtEJZeroAmtMnem                   RJPrtEJZeroAmtMnem
#define  PrtElec                            RJPrtElec
#define  PrtEndValidation                   RJPrtEndValidation
#define  PrtEPTError                        RJPrtEPTError
#define  PrtEPTStub                         RJPrtEPTStub
#define  PrtEPTStub_RJ                      RJPrtEPTStub_RJ
#define  PrtEPTStub_TH                      RJPrtEPTStub_TH
#define  PrtErrCorr                         RJPrtErrCorr
#define  PrtErrCorr_EJ                      RJPrtErrCorr_EJ
#define  PrtErrCorr_J                       RJPrtErrCorr_J
#define  PrtEtkIn                           RJPrtEtkIn
#define  PrtEtkIn_EJ                        RJPrtEtkIn_EJ
#define  PrtEtkIn_RJ                        RJPrtEtkIn_RJ
#define  PrtEtkIn_SP                        RJPrtEtkIn_SP
#define  PrtEtkIn_TH                        RJPrtEtkIn_TH
#define  PrtEtkIn_VL                        RJPrtEtkIn_VL
#define  PrtEtkOut                          RJPrtEtkOut
#define  PrtEtkOut_EJ                       RJPrtEtkOut_EJ
#define  PrtEtkOut_RJ                       RJPrtEtkOut_RJ
#define  PrtEtkOut_SP                       RJPrtEtkOut_SP
#define  PrtEtkOut_TH                       RJPrtEtkOut_TH
#define  PrtEtkOut_VL                       RJPrtEtkOut_VL
#define  PrtEuroTender                      RJPrtEuroTender
#define  PrtEuroTender_EJ                   RJPrtEuroTender_EJ
#define  PrtEuroTender_RJ                   RJPrtEuroTender_RJ
#define  PrtEuroTender_SP                   RJPrtEuroTender_SP
#define  PrtEuroTender_TH                   RJPrtEuroTender_TH
#define  PrtFeed                            RJPrtFeed
#define  PrtFillSpace                       RJPrtFillSpace
#define  PrtForeignTender                   RJPrtForeignTender
#define  PrtForeignTender_EJ                RJPrtForeignTender_EJ
#define  PrtForeignTender_RJ                RJPrtForeignTender_RJ
#define  PrtForeignTender_SP                RJPrtForeignTender_SP
#define  PrtForeignTender_TH                RJPrtForeignTender_TH
#define  PrtForeignTender_VL                RJPrtForeignTender_VL
#define  PrtFSCredit                        RJPrtFSCredit
#define  PrtGet1Line                        RJPrtGet1Line
#define  PrtGet24Mnem                       RJPrtGet24Mnem
#define  PrtGetAdj                          RJPrtGetAdj
#define  PrtGetAllProduct                   RJPrtGetAllProduct
#define  PrtMakeDateString                  RJPrtMakeDateString
#define  PrtGetDate                         RJPrtGetDate
#define  PrtGetJobInDate                    RJPrtGetJobInDate
#define  PrtGetJobOutDate                   RJPrtGetJobOutDate
#define  PrtGetLead                         RJPrtGetLead
#define  PrtGetMoneyMnem                    RJPrtGetMoneyMnem
#define  PrtGetOffTend                      RJPrtGetOffTend
#define  PrtGetScale                        RJPrtGetScale
#define  PrtGetStatus                       RJPrtGetStatus
#define  PrtGetTaxMod                       RJPrtGetTaxMod
#define  PrtGetTaxMod2                      RJPrtGetTaxMod2
#define  PrtGetVoid                         RJPrtGetVoid
#define  PrtGetReturns                      RJPrtGetReturns
#define  PrtInFeed                          RJPrtInFeed
#define  PrtInitialize                      RJPrtInitialize
#define  PrtIsIDiscInWorkBuff               RJPrtIsIDiscInWorkBuff
#define  PrtIsItemInWorkBuff                RJPrtIsItemInWorkBuff
#define  PrtItemAffection                   RJPrtItemAffection
#define  PrtItemCoupon                      RJPrtItemCoupon
#define  PrtItemDisc                        RJPrtItemDisc
#define  PrtItemMisc                        RJPrtItemMisc
#define  PrtItemModifier                    RJPrtItemModifier
#define  PrtItemMulti                       RJPrtItemMulti
#define  PrtItemOther                       RJPrtItemOther
#define  PrtItemPrint                       RJPrtItemPrint
#define  PrtItemRegDisc                     RJPrtItemRegDisc
#define  PrtItemRegDisc_EJ                  RJPrtItemRegDisc_EJ
#define  PrtItemRegDisc_RJ                  RJPrtItemRegDisc_RJ
#define  PrtItemRegDisc_SP                  RJPrtItemRegDisc_SP
#define  PrtItemRegDisc_TH                  RJPrtItemRegDisc_TH
#define  PrtItemRegDisc_VL                  RJPrtItemRegDisc_VL
#define  PrtItemSales                       RJPrtItemSales
#define  PrtItemTender                      RJPrtItemTender
#define  PrtItemTotal                       RJPrtItemTotal
#define  PrtItemTransOpen                   RJPrtItemTransOpen
#define  PrtJFolioPost                      RJPrtJFolioPost
#define  PrtJItems                          RJPrtJItems
#define  PrtJPLUBuild                       RJPrtJPLUBuild
#define  PrtJPLUNo                          RJPrtJPLUNo
#define  PrtKPCheckTarget                   RJPrtKPCheckTarget
#define  PrtKPChild                         RJPrtKPChild
#define  PrtKPCustomerName                  RJPrtKPCustomerName
#define  PrtKPEnd                           RJPrtKPEnd
#define  PrtKPHeader                        RJPrtKPHeader
#define  PrtKPInit                          RJPrtKPInit
#define  PrtKPItem                          RJPrtKPItem
#define  PrtKPNoun                          RJPrtKPNoun
#define  PrtKPOperatorName                  RJPrtKPOperatorName
#define  PrtKPPM                            RJPrtKPPM
#define  PrtKPQty                           RJPrtKPQty
#define  PrtKPSeatNo                        RJPrtKPSeatNo
#define  PrtKPSetMenuItem                   RJPrtKPSetMenuItem
#define  PrtKPTotal                         RJPrtKPTotal
#define  PrtKPTrailer                       RJPrtKPTrailer
#define  PrtKPWeight                        RJPrtKPWeight
#define  PrtModCustName_EJ                  RJPrtModCustName_EJ
#define  PrtModCustName_RJ                  RJPrtModCustName_RJ
#define  PrtModCustName_SP                  RJPrtModCustName_SP
#define  PrtModCustName_TH                  RJPrtModCustName_TH
#define  PrtModDisc                         RJPrtModDisc
#define  PrtModDisc_SP                      RJPrtModDisc_SP
#define  PrtModDisc_VL                      RJPrtModDisc_VL
#define  PrtModPerson_EJ                    RJPrtModPerson_EJ
#define  PrtModPerson_RJ                    RJPrtModPerson_RJ
#define  PrtModPerson_SP                    RJPrtModPerson_SP
#define  PrtModPerson_TH                    RJPrtModPerson_TH
#define  PrtModTable_EJ                     RJPrtModTable_EJ
#define  PrtModTable_RJ                     RJPrtModTable_RJ
#define  PrtModTable_SP                     RJPrtModTable_SP
#define  PrtModTable_TH                     RJPrtModTable_TH
#define  PrtMoney                           RJPrtMoney
#define  PrtMoney_RJ                        RJPrtMoney_RJ
#define  PrtMoney_SP                        RJPrtMoney_SP
#define  PrtMoney_TH                        RJPrtMoney_TH
#define  PrtMoneyHeader                     RJPrtMoneyHeader
#define  PrtMoneyHeader_RJ                  RJPrtMoneyHeader_RJ
#define  PrtMoneyHeader_SP                  RJPrtMoneyHeader_SP
#define  PrtMulChk_EJ                       RJPrtMulChk_EJ
#define  PrtMulChk_RJ                       RJPrtMulChk_RJ
#define  PrtMulChk_SP                       RJPrtMulChk_SP
#define  PrtMulChk_TH                       RJPrtMulChk_TH
#define  PrtMulPost_EJ                      RJPrtMulPost_EJ
#define  PrtMulPost_RJ                      RJPrtMulPost_RJ
#define  PrtMulPost_SP                      RJPrtMulPost_SP
#define  PrtMulPost_TH                      RJPrtMulPost_TH
#define  PrtMulPostTotal_EJ                 RJPrtMulPostTotal_EJ
#define  PrtMulPostTotal_RJ                 RJPrtMulPostTotal_RJ
#define  PrtMulPostTotal_SP                 RJPrtMulPostTotal_SP
#define  PrtMulPostTotal_TH                 RJPrtMulPostTotal_TH
#define  PrtMulti                           RJPrtMulti
#define  PrtMultiPost                       RJPrtMultiPost
#define  PrtMultiPostTotal                  RJPrtMultiPostTotal
#define  PrtMultiTotal                      RJPrtMultiTotal
#define  PrtMulTotal_EJ                     RJPrtMulTotal_EJ
#define  PrtMulTotal_RJ                     RJPrtMulTotal_RJ
#define  PrtMulTotal_SP                     RJPrtMulTotal_SP
#define  PrtMulTotal_TH                     RJPrtMulTotal_TH
#define  PrtNewChk                          RJPrtNewChk
#define  PrtNewChk_EJ                       RJPrtNewChk_EJ
#define  PrtNewChk_RJ                       RJPrtNewChk_RJ
#define  PrtNewChk_SP                       RJPrtNewChk_SP
#define  PrtNewChk_TH                       RJPrtNewChk_TH
#define  PrtNoSale                          RJPrtNoSale
#define  PrtNoSale_EJ                       RJPrtNoSale_EJ
#define  PrtNoSale_RJ                       RJPrtNoSale_RJ
#define  PrtNoSale_SP                       RJPrtNoSale_SP
#define  PrtNoSale_TH                       RJPrtNoSale_TH
#define  PrtNumber                          RJPrtNumber
#define  PrtNumber_EJ                       RJPrtNumber_EJ
#define  PrtNumber_RJ                       RJPrtNumber_RJ
#define  PrtNumber_SP                       RJPrtNumber_SP
#define  PrtNumber_TH                       RJPrtNumber_TH
#define  PrtOutFeed                         RJPrtOutFeed
#define  PrtPaidOut                         RJPrtPaidOut
#define  PrtPaidOut_EJ                      RJPrtPaidOut_EJ
#define  PrtPaidOut_RJ                      RJPrtPaidOut_RJ
#define  PrtPaidOut_SP                      RJPrtPaidOut_SP
#define  PrtPaidOut_TH                      RJPrtPaidOut_TH
#define  PrtPaidOut_VL                      RJPrtPaidOut_VL
#define  PrtParkReceipt                     RJPrtParkReceipt
#define  PrtParkReceipt_EJ                  RJPrtParkReceipt_EJ
#define  PrtParkReceipt_RJ                  RJPrtParkReceipt_RJ
#define  PrtParkReceipt_SP                  RJPrtParkReceipt_SP
#define  PrtParkReceipt_TH                  RJPrtParkReceipt_TH
#define  PrtPLU                             RJPrtPLU
#define  PrtPmgWait                         RJPrtPmgWait
#define  PrtPortion                         RJPrtPortion
#define  PrtPortion2                        RJPrtPortion2
#define  PrtPortion3                        RJPrtPortion3
#define  PrtPostRct                         RJPrtPostRct
#define  PrtPostRct_EJ                      RJPrtPostRct_EJ
#define  PrtPostRct_RJ                      RJPrtPostRct_RJ
#define  PrtPostRct_SP                      RJPrtPostRct_SP
#define  PrtPostRct_TH                      RJPrtPostRct_TH
#define  PrtPrint                           RJPrtPrint
#define  PrtPrintCpEpt                      RJPrtPrintCpEpt
#define  PrtPrintDemand                     RJPrtPrintDemand
#define  PrtPrintSummaryReceipt             RJPrtPrintSummaryReceipt
#define  PrtPrintf                          RJPrtPrintf
#define  PrtPrintLine                       RJPrtPrintLine
#define  PrtPrintLineImmediate              RJPrtPrintLineImmediate
#define  PrtPrintItem                       RJPrtPrintItem
#define  PrtPrintSplit                      RJPrtPrintSplit
#define  PrtPrintTran                       RJPrtPrintTran
#define  PrtProm_R                          RJPrtProm_R
#define  PrtProm_TH                         RJPrtProm_TH
#define  PrtPromotion                       RJPrtPromotion
#define  PrtPVoid                           RJPrtPVoid
#define  PrtPVoid_EJ                        RJPrtPVoid_EJ
#define  PrtPVoid_RJ                        RJPrtPVoid_RJ
#define  PrtPVoid_SP                        RJPrtPVoid_SP
#define  PrtPVoid_TH                        RJPrtPVoid_TH
#define  PrtEndorse                         RJPrtEndorse            /* DTREE#2 */
#define  PrtSPEndorsHeadH                   RJPrtSPEndorsHeadH      /* DTREE#2 */
#define  PrtSPEndorsMnemH1                  RJPrtSPEndorsMnemH1     /* DTREE#2 */
#define  PrtSPEndorsMnemH2                  RJPrtSPEndorsMnemH2     /* DTREE#2 */
#define  PrtSPEndorsTrail2                  RJPrtSPEndorsTrail2     /* DTREE#2 */
#define  PrtSPEndorsTrail3                  RJPrtSPEndorsTrail3     /* DTREE#2 */
#define  PrtSPEndorsHeadV                   RJPrtSPEndorsHeadV      /* DTREE#2 */
#define  PrtSPEndorsMnemAmtV1               RJPrtSPEndorsMnemAmtV1  /* DTREE#2 */
#define  PrtSPEndorsMnemAmtV2               RJPrtSPEndorsMnemAmtV2  /* DTREE#2 */
#define  PrtSPEndorsTrail1                  RJPrtSPEndorsTrail1     /* DTREE#2 */
#define  PrtEndorse_VL                      RJPrtEndorse_VL
#define  PrtVLEndosHead                     RJPrtVLEndosHead
#define  PrtVLEndosTrngHead                 RJPrtVLEndosTrngHead
#define  PrtVLEndosTrail                    RJPrtVLEndosTrail
#define  PrtVLEndosMnemAmt                  RJPrtVLEndosMnemAmt
#define  PrtVLEndosMnemCSAmt                RJPrtVLEndosMnemCSAmt
#define  PrtRectCompul                      RJPrtRectCompul
#define  PrtRecvOnAcnt                      RJPrtRecvOnAcnt
#define  PrtRecvOnAcnt_EJ                   RJPrtRecvOnAcnt_EJ
#define  PrtRecvOnAcnt_RJ                   RJPrtRecvOnAcnt_RJ
#define  PrtRecvOnAcnt_SP                   RJPrtRecvOnAcnt_SP
#define  PrtRecvOnAcnt_TH                   RJPrtRecvOnAcnt_TH
#define  PrtRecvOnAcnt_VL                   RJPrtRecvOnAcnt_VL
#define  PrtReorder                         RJPrtReorder
#define  PrtReorder_EJ                      RJPrtReorder_EJ
#define  PrtReorder_RJ                      RJPrtReorder_RJ
#define  PrtReorder_SP                      RJPrtReorder_SP
#define  PrtReorder_TH                      RJPrtReorder_TH
#define  PrtResetLog                        RJPrtResetLog
#define  PrtResetQtyDecimal                 RJPrtResetQtyDecimal
#define  PrtRFeed                           RJPrtRFeed
#define  PrtRItems                          RJPrtRItems
#define  PrtRJAmtMnem                       RJPrtRJAmtMnem
#define  PrtRJAmtMnemShift                  RJPrtRJAmtMnemShift
#define  PrtRJAmtSym                        RJPrtRJAmtSym
#define  PrtRJAmtSymEuro                    RJPrtRJAmtSymEuro
#define  PrtRJAmtSymP                       RJPrtRJAmtSymP
#define  PrtRJChild                         RJPrtRJChild
#define  PrtRJLinkPLU                       RJPrtRJLinkPLU
#define  PrtRJCoupon                        RJPrtRJCoupon
#define  PrtRJCPRespText                    RJPrtRJCPRespText
#define  PrtRJCPRoomCharge                  RJPrtRJCPRoomCharge
#define  PrtRJCPRspMsgText                  RJPrtRJCPRspMsgText
#define  PrtRJCustomerName                  RJPrtRJCustomerName
#define  PrtRJDoubleHead                    RJPrtRJDoubleHead
#define  PrtRJEPTError                      RJPrtRJEPTError
#define  PrtRJEtkCode                       RJPrtRJEtkCode
#define  PrtRJEuro                          RJPrtRJEuro
#define  PrtRJForeign1                      RJPrtRJForeign1
#define  PrtRJForeign2                      RJPrtRJForeign2
#define  PrtRJForeignQtyFor                 RJPrtRJForeignQtyFor
#define  PrtRJGuest                         RJPrtRJGuest
#define  PrtRJHead                          RJPrtRJHead
#define  PrtRJJobTimeIn                     RJPrtRJJobTimeIn
#define  PrtRJJobTimeOut                    RJPrtRJJobTimeOut
#define  PrtRJKitchen                       RJPrtRJKitchen
#define  PrtRJMnem                          RJPrtRJMnem
#define  PrtRJMnemCount                     RJPrtRJMnemCount
#define  PrtRJModScale                      RJPrtRJModScale
#define  PrtRJMoneyForeign                  RJPrtRJMoneyForeign
#define  PrtRJMulChk                        RJPrtRJMulChk
#define  PrtRJMultiSeatNo                   RJPrtRJMultiSeatNo
#define  PrtRJNumber                        RJPrtRJNumber
#define  PrtRJMnemNumber                    RJPrtRJMnemNumber
#define  PrtRJOffline                       RJPrtRJOffline
#define  PrtRJOffTend                       RJPrtRJOffTend
#define  PrtRJPerDisc                       RJPrtRJPerDisc
#define  PrtRJQty                           RJPrtRJQty
#define  PrtRJLinkQty                       RJPrtRJLinkQty
#define  PrtRJQtyFor                        RJPrtRJQtyFor
#define  PrtRJResetLog                      RJPrtRJResetLog
#define  PrtRJResetLog3                     RJPrtRJResetLog3
#define  PrtRJResetLog4                     RJPrtRJResetLog4
#define  PrtRJSeatNo                        RJPrtRJSeatNo
#define  PrtRJSeatNo2                       RJPrtRJSeatNo2
#define  PrtRJTaxMod                        RJPrtRJTaxMod
#define  PrtRJTblPerson                     RJPrtRJTblPerson
#define  PrtRJTickTrail_21                  RJPrtRJTickTrail_21
#define  PrtRJTickTrail_24                  RJPrtRJTickTrail_24
#define  PrtRJTrail1_21                     RJPrtRJTrail1_21
#define  PrtRJTrail1_24                     RJPrtRJTrail1_24
#define  PrtRJTrail2                        RJPrtRJTrail2
#define  PrtRJTranNum                       RJPrtRJTranNum
#define  PrtRJVATAppl                       RJPrtRJVATAppl
#define  PrtRJVATApplShift                  RJPrtRJVATApplShift
#define  PrtRJVoid                          RJPrtRJVoid
#define  PrtRJWaiTaxMod                     RJPrtRJWaiTaxMod
#define  PrtRJWaiter                        RJPrtRJWaiter
#define  PrtRJWeight                        RJPrtRJWeight
#define  PrtRJZAMnemPShift                  RJPrtRJZAMnemPShift
#define  PrtRJZAMnemShift                   RJPrtRJZAMnemShift
#define  PrtRJZeroAmtMnem                   RJPrtRJZeroAmtMnem
#define  PrtRJZeroAmtMnemP                  RJPrtRJZeroAmtMnemP
#define  PrtRPLUNo                          RJPrtRPLUNo
#define  PrtSDouble                         RJPrtSDouble
#define  PrtServTotal                       RJPrtServTotal
#define  PrtServTotal_EJ                    RJPrtServTotal_EJ
#define  PrtServTotal_RJ                    RJPrtServTotal_RJ
#define  PrtServTotal_SP                    RJPrtServTotal_SP
#define  PrtServTotal_SPVL                  RJPrtServTotal_SPVL
#define  PrtServTotal_TH                    RJPrtServTotal_TH
#define  PrtServTotal_VL                    RJPrtServTotal_VL
#define  PrtServTotalPost                   RJPrtServTotalPost
#define  PrtServTotalPost_EJ                RJPrtServTotalPost_EJ
#define  PrtServTotalPost_RJ                RJPrtServTotalPost_RJ
#define  PrtServTotalPost_SP                RJPrtServTotalPost_SP
#define  PrtServTotalPost_SPVL              RJPrtServTotalPost_SPVL
#define  PrtServTotalPost_TH                RJPrtServTotalPost_TH
#define  PrtServTotalPost_VL                RJPrtServTotalPost_VL
#define  PrtServTotalStubPost               RJPrtServTotalStubPost
#define  PrtSET                             RJPrtSET
#define  PrtSET_EJ                          RJPrtSET_EJ
#define  PrtSET_RJ                          RJPrtSET_RJ
#define  PrtSET_SP                          RJPrtSET_SP
#define  PrtSET_TH                          RJPrtSET_TH
#define  PrtSetChildNotOrder                RJPrtSetChildNotOrder
#define  PrtSetChildPriority                RJPrtSetChildPriority
#define  PrtSetFailKP                       RJPrtSetFailKP
#define  PrtSetItem                         RJPrtSetItem
#define  PrtSETKP_RJ                        RJPrtSETKP_RJ
#define  PrtSETKP_TH                        RJPrtSETKP_TH
#define  PrtSetMnemSymAmt                   RJPrtSetMnemSymAmt
#define  PrtSetModDisc_EJ                   RJPrtSetModDisc_EJ
#define  PrtSetModDisc_RJ                   RJPrtSetModDisc_RJ
#define  PrtSetModDisc_TH                   RJPrtSetModDisc_TH
#define  PrtSetNumber                       RJPrtSetNumber
#define  PrtSetQtyDecimal                   RJPrtSetQtyDecimal
#define  PrtSetRJColumn                     RJPrtSetRJColumn
#define  PrtSetSalesCouponQTY               RJPrtSetSalesCouponQTY
#define  PrtShrAltr                         RJPrtShrAltr
#define  PrtShrAltrRetry                    RJPrtShrAltrRetry
#define  PrtShrEnd                          RJPrtShrEnd
#define  PrtShrFirstRetryPrc                RJPrtShrFirstRetryPrc
#define  PrtShrInit                         RJPrtShrInit
#define  PrtShrInitReverse                  RJPrtShrInitReverse
#define  PrtShrLockSub                      RJPrtShrLockSub
#define  PrtShrPartialSend                  RJPrtShrPartialSend
#define  PrtShrPrint                        RJPrtShrPrint
#define  PrtShrRegSend                      RJPrtShrRegSend
#define  PrtShrRetryPrc                     RJPrtShrRetryPrc
#define  PrtShrSupSend                      RJPrtShrSupSend
#define  PrtShrTermLock                     RJPrtShrTermLock
#define  PrtShrTermUnLock                   RJPrtShrTermUnLock
#define  PrtShrWriteFirstRetry              RJPrtShrWriteFirstRetry
#define  PrtShrWriteRetry                   RJPrtShrWriteRetry
#define  PrtShrWriteRetry_Reg               RJPrtShrWriteRetry_Reg
#define  PrtSlipInitial                     RJPrtSlipInitial
#define  PrtSlipPmgWait                     RJPrtSlipPmgWait
#define  PrtSlpCompul                       RJPrtSlpCompul
#define  PrtSlpRel                          RJPrtSlpRel
#define  PrtSoftCheckTotal                  RJPrtSoftCheckTotal
#define  PrtSoftCheckTotal_EJ               RJPrtSoftCheckTotal_EJ
#define  PrtSoftCheckTotal_RJ               RJPrtSoftCheckTotal_RJ
#define  PrtSoftCheckTotal_SP               RJPrtSoftCheckTotal_SP
#define  PrtSoftCheckTotal_SPVL             RJPrtSoftCheckTotal_SPVL
#define  PrtSoftCheckTotal_TH               RJPrtSoftCheckTotal_TH
#define  PrtSoftCheckTotal_VL               RJPrtSoftCheckTotal_VL
#define  PrtSoftProm                        RJPrtSoftProm
#define  PrtSPAmtSymEuro                    RJPrtSPAmtSymEuro
#define  PrtSPCancel                        RJPrtSPCancel
#define  PrtSPChargeTips                    RJPrtSPChargeTips
#define  PrtSPChild                         RJPrtSPChild
#define  PrtSPLinkPLU                       RJPrtSPLinkPLU
#define  PrtSPChkPaid                       RJPrtSPChkPaid
#define  PrtSPCoupon                        RJPrtSPCoupon
#define  PrtSPCPOffTend                     RJPrtSPCPOffTend
#define  PrtSPCPRoomCharge                  RJPrtSPCPRoomCharge
#define  PrtSPCPRspMsgText                  RJPrtSPCPRspMsgText
#define  PrtSPCustomerName                  RJPrtSPCustomerName
#define  PrtSPDiscount                      RJPrtSPDiscount
#define  PrtSPEtkTimeIn                     RJPrtSPEtkTimeIn
#define  PrtSPEtkTimeOut                    RJPrtSPEtkTimeOut
#define  PrtSPEuro                          RJPrtSPEuro
#define  PrtSpForeign                       RJPrtSpForeign
#define  PrtSPForeignQtyFor                 RJPrtSPForeignQtyFor
#define  PrtSPGCTransfer                    RJPrtSPGCTransfer
#define  PrtSPGCTranTrail                   RJPrtSPGCTranTrail
#define  PrtSPGstChkNo                      RJPrtSPGstChkNo
#define  PrtSPHeader1                       RJPrtSPHeader1
#define  PrtSPHeader2                       RJPrtSPHeader2
#define  PrtSPHeader3                       RJPrtSPHeader3
#define  PrtSPItems                         RJPrtSPItems
#define  PrtSPMAmtShift                     RJPrtSPMAmtShift
#define  PrtSPMnemAmt                       RJPrtSPMnemAmt
#define  PrtSPMnemNativeAmt                 RJPrtSPMnemNativeAmt
#define  PrtSPMnemTaxAmt                    RJPrtSPMnemTaxAmt
#define  PrtSPMnemTaxQty                    RJPrtSPMnemTaxQty
#define  PrtSPMnlWeight                     RJPrtSPMnlWeight
#define  PrtSPMoneyForeign                  RJPrtSPMoneyForeign
#define  PrtSPMultiSeatNo                   RJPrtSPMultiSeatNo
#define  PrtSPOffline                       RJPrtSPOffline
#define  PrtSPPLUBuild                      RJPrtSPPLUBuild
#define  PrtSPPLUNo                         RJPrtSPPLUNo
#define  PrtSPQty                           RJPrtSPQty
#define  PrtSPLinkQty                       RJPrtSPLinkQty
#define  PrtSPQtyFor                        RJPrtSPQtyFor
#define  PrtSPSeatNo                        RJPrtSPSeatNo
#define  PrtSPServiceTotal                  RJPrtSPServiceTotal
#define  PrtSPServTaxSum                    RJPrtSPServTaxSum
#define  PrtSPTaxAmt                        RJPrtSPTaxAmt
#define  PrtSPTaxMnem                       RJPrtSPTaxMnem
#define  PrtSPTaxMod                        RJPrtSPTaxMod
#define  PrtSPTaxRateAmt                    RJPrtSPTaxRateAmt
#define  PrtSPTblPerson                     RJPrtSPTblPerson
#define  PrtSPTipsPO                        RJPrtSPTipsPO
#define  PrtSPTrail1                        RJPrtSPTrail1
#define  PrtSPTrail2                        RJPrtSPTrail2
#define  PrtSPTranMnem                      RJPrtSPTranMnem
#define  PrtSPTranNumber                    RJPrtSPTranNumber
#define  PrtSPTrayCount                     RJPrtSPTrayCount
#define  PrtSPVLHead                        RJPrtSPVLHead
#define  PrtSPVLHead1                       RJPrtSPVLHead1
#define  PrtSPVLHead2                       RJPrtSPVLHead2
#define  PrtSPVLHead3                       RJPrtSPVLHead3
#define  PrtSPVLInit                        RJPrtSPVLInit
#define  PrtSPVLTrail                       RJPrtSPVLTrail
#define  PrtSPVoidNumber                    RJPrtSPVoidNumber
#define  PrtSPVoidMnemNumber                RJPrtSPVoidMnemNumber
#define  PrtSPWeight                        RJPrtSPWeight
#define  PrtStoreRecall                     RJPrtStoreRecall
#define  PrtStoreRecall_EJ                  RJPrtStoreRecall_EJ
#define  PrtStoreRecall_RJ                  RJPrtStoreRecall_RJ
#define  PrtStoreRecall_SP                  RJPrtStoreRecall_SP
#define  PrtStoreRecall_TH                  RJPrtStoreRecall_TH
#define  PrtSup1stTrailer                   RJPrtSup1stTrailer
#define  PrtSup2ndTrailer                   RJPrtSup2ndTrailer
#define  PrtSup3rdTrailer                   RJPrtSup3rdTrailer
#define  PrtSupAge                          RJPrtSupAge
#define  PrtSupBcas                         RJPrtSupBcas
#define  PrtSupCashierNo                    RJPrtSupCashierNo
#define  PrtSupCashWaitFile                 RJPrtSupCashWaitFile
#define  PrtSupChkType                      RJPrtSupChkType
#define  PrtSupComData                      RJPrtSupComData
#define  PrtSupCompSlip                     RJPrtSupCompSlip
#define  PrtSupCpm                          RJPrtSupCpm
#define  PrtSupCPN                          RJPrtSupCPN
#define  PrtSupCPNFile                      RJPrtSupCPNFile
#define  PrtSupCPNFile_s                    RJPrtSupCPNFile_s
#define  PrtSupCstrData                     RJPrtSupCstrData
#define  PrtSupCurrency                     RJPrtSupCurrency
#define  PrtSupDEPT                         RJPrtSupDEPT
#define  PrtSupDEPTFile                     RJPrtSupDEPTFile
#define  PrtSupDEPTFile_s                   RJPrtSupDEPTFile_s
#define  PrtSupDeptNoMenu                   RJPrtSupDeptNoMenu
#define  PrtSupDispPara                     RJPrtSupDispPara
#define  PrtSupEJ                           RJPrtSupEJ
#define  PrtSupEmployeeNo                   RJPrtSupEmployeeNo
#define  PrtSupErrorCode                    RJPrtSupErrorCode
#define  PrtSupETKFile                      RJPrtSupETKFile
#define  PrtSupETKFile_s                    RJPrtSupETKFile_s
#define  PrtSupFlexMem                      RJPrtSupFlexMem
#define  PrtSupForeignTender_RJ             RJPrtSupForeignTender_RJ
#define  PrtSupFSC                          RJPrtSupFSC
#define  PrtSupFxDrive                      RJPrtSupFxDrive
#define  PrtSupGCF                          RJPrtSupGCF
#define  PrtSupGCF_s                        RJPrtSupGCF_s
#define  PrtSupGCFClose                     RJPrtSupGCFClose
#define  PrtSupGCNo                         RJPrtSupGCNo
#define  PrtSupHeader                       RJPrtSupHeader
#define  PrtSupHourly                       RJPrtSupHourly
#define  PrtSupHourlyAct                    RJPrtSupHourlyAct
#define  PrtSupItoa                         RJPrtSupItoa
#define  PrtSupKdsIp                        RJPrtSupKdsIp
#define  PrtSupLoanPickup                   RJPrtSupLoanPickup
#define  PrtSupLoanPickup_RJ                RJPrtSupLoanPickup_RJ
#define  PrtSupLoanPickup_SP                RJPrtSupLoanPickup_SP
#define  PrtSupLoanPickup_VL                RJPrtSupLoanPickup_VL
#define  PrtSupMaintETKFl                   RJPrtSupMaintETKFl
#define  PrtSupMaintETKFl_s                 RJPrtSupMaintETKFl_s
#define  PrtSupMakeData                     RJPrtSupMakeData
#define  PrtSupMakeEtkFl                    RJPrtSupMakeEtkFl
#define  PrtSupMDC                          RJPrtSupMDC
#define  PrtSupMenuPLU                      RJPrtSupMenuPLU
#define  PrtSupMenuPLU_s                    RJPrtSupMenuPLU_s
#define  PrtSupMnemData                     RJPrtSupMnemData
#define  PrtSupOepData                      RJPrtSupOepData
#define  PrtSupOpeStatus                    RJPrtSupOpeStatus
#define  PrtSupPigRule                      RJPrtSupPigRule
#define  PrtSupPLU                          RJPrtSupPLU
#define  PrtSupPLU_s                        RJPrtSupPLU_s
#define  PrtSupPLUFile                      RJPrtSupPLUFile
#define  PrtSupPLUFile_s                    RJPrtSupPLUFile_s
#define  PrtSupPLUNoMenu                    RJPrtSupPLUNoMenu
#define  PrtSupPPI                          RJPrtSupPPI
#define  PrtSupPresetAmount                 RJPrtSupPresetAmount
#define  PrtSupRegFin                       RJPrtSupRegFin
#define  PrtSupRemoveSlip                   RJPrtSupRemoveSlip
#define  PrtSupRest                         RJPrtSupRest
#define  PrtSupRJFeed                       RJPrtSupRJFeed
#define  PrtSupRJVoid                       RJPrtSupRJVoid
#define  PrtSupRound                        RJPrtSupRound
#define  PrtSupServiceTime                  RJPrtSupServiceTime
#define  PrtSupSPHead                       RJPrtSupSPHead
#define  PrtSupSPHeadLine                   RJPrtSupSPHeadLine
#define  PrtSupSPTrail1                     RJPrtSupSPTrail1
#define  PrtSupSPTrail2                     RJPrtSupSPTrail2
#define  PrtSupSPTrailer                    RJPrtSupSPTrailer
#define  PrtSupStoRegNo                     RJPrtSupStoRegNo
#define  PrtSupSupLevel                     RJPrtSupSupLevel
#define  PrtSupTally                        RJPrtSupTally
#define  PrtSupTare                         RJPrtSupTare
#define  PrtSupTaxRate                      RJPrtSupTaxRate
#define  PrtSupTaxTbl                       RJPrtSupTaxTbl
#define  PrtSupTHVoid                       RJPrtSupTHVoid
#define  PrtSupTOD                          RJPrtSupTOD
#define  PrtSupTrailer                      RJPrtSupTrailer
#define  PrtSupTrans                        RJPrtSupTrans
#define  PrtSupTtlKeyCtl                    RJPrtSupTtlKeyCtl
#define  PrtSupVLForeignTend                RJPrtSupVLForeignTend
#define  PrtSupVLForQty                     RJPrtSupVLForQty
#define  PrtSupVLHead                       RJPrtSupVLHead
#define  PrtSupVLLoanPickup                 RJPrtSupVLLoanPickup
#define  PrtSupVLModifier                   RJPrtSupVLModifier
#define  PrtSupVLTrail                      RJPrtSupVLTrail
#define  PrtSupWFClose                      RJPrtSupWFClose
#define  PrtTakeToKP                        RJPrtTakeToKP
#define  PrtTax                             RJPrtTax
#define  PrtTender                          RJPrtTender
#define  PrtTender_EJ                       RJPrtTender_EJ
#define  PrtTender_RJ                       RJPrtTender_RJ
#define  PrtTender_SP                       RJPrtTender_SP
#define  PrtTender_TH                       RJPrtTender_TH
#define  PrtTender_VL                       RJPrtTender_VL
#define  PrtTHAmtMnem                       RJPrtTHAmtMnem
#define  PrtTHAmtMnemMnem                   RJPrtTHAmtMnemMnem
#define  PrtTHAmtSym                        RJPrtTHAmtSym
#define  PrtTHAmtSymEuro                    RJPrtTHAmtSymEuro
#define  PrtTHAmtTaxMnem                    RJPrtTHAmtTaxMnem
#define  PrtTHChild                         RJPrtTHChild
#define  PrtTHLinkPLU                       RJPrtTHLinkPLU
#define  PrtTHCoupon                        RJPrtTHCoupon
#define  PrtTHCPRespText                    RJPrtTHCPRespText
#define  PrtTHCPRoomCharge                  RJPrtTHCPRoomCharge
#define  PrtTHCPRspMsgText                  RJPrtTHCPRspMsgText
#define  PrtTHCustomerName                  RJPrtTHCustomerName
#define  PrtTHDiscItems                     RJPrtTHDiscItems
#define  PrtTHDoubleHead                    RJPrtTHDoubleHead
#define  PrtTHEPTError                      RJPrtTHEPTError
#define  PrtThermSupAge                     RJPrtThermSupAge
#define  PrtThermSupRest                    RJPrtThermSupRest
#define  PrtTHEtkCode                       RJPrtTHEtkCode
#define  PrtTHEtkOut                        RJPrtTHEtkOut
#define  PrtTHEuro                          RJPrtTHEuro
#define  PrtTHForeign                       RJPrtTHForeign
#define  PrtTHForeignQtyFor                 RJPrtTHForeignQtyFor
#define  PrtTHGuest                         RJPrtTHGuest
#define  PrtTHHead                          RJPrtTHHead
#define  PrtTHItems                         RJPrtTHItems
#define  PrtTHJobTimeIn                     RJPrtTHJobTimeIn
#define  PrtTHJobTimeOut                    RJPrtTHJobTimeOut
#define  PrtTHKitchen                       RJPrtTHKitchen
#define  PrtTHMAmtShift                     RJPrtTHMAmtShift
#define  PrtTHMnem                          RJPrtTHMnem
#define  PrtTHMnemCount                     RJPrtTHMnemCount
#define  PrtTHMoneyForeign                  RJPrtTHMoneyForeign
#define  PrtTHMulChk                        RJPrtTHMulChk
#define  PrtTHMultiSeatNo                   RJPrtTHMultiSeatNo
#define  PrtTHNumber                        RJPrtTHNumber
#define  PrtTHMnemNumber                    RJPrtTHMnemNumber
#define  PrtTHOffline                       RJPrtTHOffline
#define  PrtTHOffTend                       RJPrtTHOffTend
#define  PrtTHPerDisc                       RJPrtTHPerDisc
#define  PrtTHPLUNo                         RJPrtTHPLUNo
#define  PrtTHQty                           RJPrtTHQty
#define  PrtTHLinkQty                       RJPrtTHLinkQty
#define  PrtThrmSupBcas                     RJPrtThrmSupBcas
#define  PrtThrmSupCashierNo                RJPrtThrmSupCashierNo
#define  PrtThrmSupCashWaitFile             RJPrtThrmSupCashWaitFile
#define  PrtThrmSupComData                  RJPrtThrmSupComData
#define  PrtThrmSupCpm                      RJPrtThrmSupCpm
#define  PrtThrmSupCPN                      RJPrtThrmSupCPN
#define  PrtThrmSupCPNFile                  RJPrtThrmSupCPNFile
#define  PrtThrmSupCstrData                 RJPrtThrmSupCstrData
#define  PrtThrmSupCurrency                 RJPrtThrmSupCurrency
#define  PrtThrmSupDEPT                     RJPrtThrmSupDEPT
#define  PrtThrmSupDEPTFile                 RJPrtThrmSupDEPTFile
#define  PrtThrmSupDeptNoMenu               RJPrtThrmSupDeptNoMenu
#define  PrtThrmSupDispPara                 RJPrtThrmSupDispPara
#define  PrtThrmSupEmployeeNo               RJPrtThrmSupEmployeeNo
#define  PrtThrmSupErrorCode                RJPrtThrmSupErrorCode
#define  PrtThrmSupETKFile                  RJPrtThrmSupETKFile
#define  PrtThrmSupFlexMem                  RJPrtThrmSupFlexMem
#define  PrtThrmSupFormTrailer              RJPrtThrmSupFormTrailer
#define  PrtThrmSupFSC                      RJPrtThrmSupFSC
#define  PrtThrmSupFxDrive                  RJPrtThrmSupFxDrive
#define  PrtThrmSupGCF                      RJPrtThrmSupGCF
#define  PrtThrmSupGCFClose                 RJPrtThrmSupGCFClose
#define  PrtThrmSupGCNo                     RJPrtThrmSupGCNo
#define  PrtThrmSupHeader                   RJPrtThrmSupHeader
#define  PrtThrmSupHourly                   RJPrtThrmSupHourly
#define  PrtThrmSupHourlyAct                RJPrtThrmSupHourlyAct
#define  PrtThrmSupKdsIp                    RJPrtThrmSupKdsIp
#define  PrtThrmSupMaintETKFl               RJPrtThrmSupMaintETKFl
#define  PrtThrmSupMakeETKFl                RJPrtThrmSupMakeETKFl
#define  PrtThrmSupMakeString               RJPrtThrmSupMakeString
#define  PrtThrmSupMDC                      RJPrtThrmSupMDC
#define  PrtThrmSupMenuPLU                  RJPrtThrmSupMenuPLU
#define  PrtThrmSupMnemData                 RJPrtThrmSupMnemData
#define  PrtThrmSupOepData                  RJPrtThrmSupOepData
#define  PrtThrmSupOpeStatus                RJPrtThrmSupOpeStatus
#define  PrtThrmSupPigRule                  RJPrtThrmSupPigRule
#define  PrtThrmSupPLU                      RJPrtThrmSupPLU
#define  PrtThrmSupPLUFile                  RJPrtThrmSupPLUFile
#define  PrtThrmSupPLUNoMenu                RJPrtThrmSupPLUNoMenu
#define  PrtThrmSupPPI                      RJPrtThrmSupPPI
#define  PrtThrmSupPresetAmount             RJPrtThrmSupPresetAmount
#define  PrtThrmSupRegFin                   RJPrtThrmSupRegFin
#define  PrtThrmSupRJFeed                   RJPrtThrmSupRJFeed
#define  PrtThrmSupRound                    RJPrtThrmSupRound
#define  PrtThrmSupServiceTime              RJPrtThrmSupServiceTime
#define  PrtThrmSupStoRegNo                 RJPrtThrmSupStoRegNo
#define  PrtThrmSupSupLevel                 RJPrtThrmSupSupLevel
#define  PrtThrmSupTally                    RJPrtThrmSupTally
#define  PrtThrmSupTare                     RJPrtThrmSupTare
#define  PrtThrmSupTaxRate                  RJPrtThrmSupTaxRate
#define  PrtThrmSupTaxTbl                   RJPrtThrmSupTaxTbl
#define  PrtThrmSupTOD                      RJPrtThrmSupTOD
#define  PrtThrmSupTrailer                  RJPrtThrmSupTrailer
#define  PrtThrmSupTrans                    RJPrtThrmSupTrans
#define  PrtThrmSupDspfline                 RJPrtThrmSupDspfline
#define  PrtThrmSupTtlKeyCtl                RJPrtThrmSupTtlKeyCtl
#define  PrtThrmSupWFClose                  RJPrtThrmSupWFClose
#define  PrtTHSeatNo                        RJPrtTHSeatNo
#define  PrtTHSeatNo2                       RJPrtTHSeatNo2
#define  PrtTHTaxMod                        RJPrtTHTaxMod
#define  PrtTHTaxRateAmt                    RJPrtTHTaxRateAmt
#define  PrtTHTblPerGC                      RJPrtTHTblPerGC
#define  PrtTHTentName						RJPrtTHTentName
#define  PrtTHTblPerson                     RJPrtTHTblPerson
#define  PrtTHTickTrail1                    RJPrtTHTickTrail1
#define  PrtTHTickTrail2                    RJPrtTHTickTrail2
#define  PrtTHTrail1                        RJPrtTHTrail1
#define  PrtTHTrail2                        RJPrtTHTrail2
#define  PrtTHTranNum                       RJPrtTHTranNum
#define  PrtTHVatAmt                        RJPrtTHVatAmt
#define  PrtTHVatMnem                       RJPrtTHVatMnem
#define  PrtTHVoid                          RJPrtTHVoid
#define  PrtTHWaiAmtMnem                    RJPrtTHWaiAmtMnem
#define  PrtTHWaiGC                         RJPrtTHWaiGC
#define  PrtTHWaiTaxMod                     RJPrtTHWaiTaxMod
#define  PrtTHWeight                        RJPrtTHWeight
#define  PrtTHZeroAmtMnem                   RJPrtTHZeroAmtMnem
#define  PrtTipsDecld                       RJPrtTipsDecld
#define  PrtTipsDecld_EJ                    RJPrtTipsDecld_EJ
#define  PrtTipsDecld_RJ                    RJPrtTipsDecld_RJ
#define  PrtTipsDecld_SP                    RJPrtTipsDecld_SP
#define  PrtTipsDecld_TH                    RJPrtTipsDecld_TH
#define  PrtTipsDecld_VL                    RJPrtTipsDecld_VL
#define  PrtTipsPaidOut                     RJPrtTipsPaidOut
#define  PrtTipsPaidOut_EJ                  RJPrtTipsPaidOut_EJ
#define  PrtTipsPaidOut_RJ                  RJPrtTipsPaidOut_RJ
#define  PrtTipsPaidOut_SP                  RJPrtTipsPaidOut_SP
#define  PrtTipsPaidOut_TH                  RJPrtTipsPaidOut_TH
#define  PrtTipsPaidOut_VL                  RJPrtTipsPaidOut_VL
#define  PrtTotal                           RJPrtTotal
#define  PrtTotal_EJ                        RJPrtTotal_EJ
#define  PrtTotal_RJ                        RJPrtTotal_RJ
#define  PrtTotal_SP                        RJPrtTotal_SP
#define  PrtTotal_SPVL                      RJPrtTotal_SPVL
#define  PrtTotal_TH                        RJPrtTotal_TH
#define  PrtTotal_VL                        RJPrtTotal_VL
#define  PrtTotalAudact                     RJPrtTotalAudact
#define  PrtTotalAudact_SPVL                RJPrtTotalAudact_SPVL
#define  PrtTotalAudact_VL                  RJPrtTotalAudact_VL
#define  PrtTotalKP_RJ                      RJPrtTotalKP_RJ
#define  PrtTotalKP_TH                      RJPrtTotalKP_TH
#define  PrtTotalOrder                      RJPrtTotalOrder
#define  PrtTotalStub                       RJPrtTotalStub
#define  PrtTrail1                          RJPrtTrail1
#define  PrtTrail1_EJ                       RJPrtTrail1_EJ
#define  PrtTrail1_RJ                       RJPrtTrail1_RJ
#define  PrtTrail1_SP                       RJPrtTrail1_SP
#define  PrtTrail1_TH                       RJPrtTrail1_TH
#define  PrtTrail2                          RJPrtTrail2
#define  PrtTrail3                          RJPrtTrail3
#define  PrtTrailEPT_SP                     RJPrtTrailEPT_SP
#define  PrtTrain_EJ                        RJPrtTrain_EJ
#define  PrtTrain_RJ                        RJPrtTrain_RJ
#define  PrtTrain_SP                        RJPrtTrain_SP
#define  PrtTrain_TH                        RJPrtTrain_TH
#define  PrtTraining                        RJPrtTraining
#define  PrtTrayTotal                       RJPrtTrayTotal
#define  PrtTrayTotal_EJ                    RJPrtTrayTotal_EJ
#define  PrtTrayTotal_RJ                    RJPrtTrayTotal_RJ
#define  PrtTrayTotal_SP                    RJPrtTrayTotal_SP
#define  PrtTrayTotal_TH                    RJPrtTrayTotal_TH
#define  PrtTrayTotal_VL                    RJPrtTrayTotal_VL
#define  PrtTrayTrail                       RJPrtTrayTrail
#define  PrtUSTax                           RJPrtUSTax
#define  PrtUSTax_EJ                        RJPrtUSTax_EJ
#define  PrtUSTax_RJ                        RJPrtUSTax_RJ
#define  PrtUSTax_SP                        RJPrtUSTax_SP
#define  PrtUSTax_TH                        RJPrtUSTax_TH
#define  PrtVAT                             RJPrtVAT
#define  PrtVAT_EJ                          RJPrtVAT_EJ
#define  PrtVAT_RJ                          RJPrtVAT_RJ
#define  PrtVAT_SP                          RJPrtVAT_SP
#define  PrtVAT_TH                          RJPrtVAT_TH
#define  PrtVATServ                         RJPrtVATServ
#define  PrtVATServ_EJ                      RJPrtVATServ_EJ
#define  PrtVATServ_RJ                      RJPrtVATServ_RJ
#define  PrtVATServ_SP                      RJPrtVATServ_SP
#define  PrtVATServ_TH                      RJPrtVATServ_TH
#define  PrtVATSubtotal                     RJPrtVATSubtotal
#define  PrtVATSubtotal_EJ                  RJPrtVATSubtotal_EJ
#define  PrtVATSubtotal_RJ                  RJPrtVATSubtotal_RJ
#define  PrtVATSubtotal_SP                  RJPrtVATSubtotal_SP
#define  PrtVATSubtotal_TH                  RJPrtVATSubtotal_TH
#define  PrtVLAccNum                        RJPrtVLAccNum
#define  PrtVLAmtMnem                       RJPrtVLAmtMnem
#define  PrtVLAmtPerMnem                    RJPrtVLAmtPerMnem
#define  PrtVLAmtPluMnem                    RJPrtVLAmtPluMnem
#define  PrtVLAmtSym                        RJPrtVLAmtSym
#define  PrtVLCasTrail                      RJPrtVLCasTrail
#define  PrtVLChgTip                        RJPrtVLChgTip
#define  PrtVLCoupon                        RJPrtVLCoupon
#define  PrtVLEtkTimeIn                     RJPrtVLEtkTimeIn
#define  PrtVLEtkTimeOut                    RJPrtVLEtkTimeOut
#define  PrtVLForeignTend                   RJPrtVLForeignTend
#define  PrtVLHead                          RJPrtVLHead
#define  PrtVLHead1                         RJPrtVLHead1
#define  PrtVLHead2                         RJPrtVLHead2
#define  PrtVLHead3                         RJPrtVLHead3
#define  PrtVLMnemAmt                       RJPrtVLMnemAmt
#define  PrtVLNumber                        RJPrtVLNumber
#define  PrtVLMnemNumber                    RJPrtVLMnemNumber
#define  PrtVLNumberCP                      RJPrtVLNumberCP
#define  PrtVLNumQty                        RJPrtVLNumQty
#define  PrtVLNumWeight                     RJPrtVLNumWeight
#define  PrtVLOffline                       RJPrtVLOffline
#define  PrtVLTender1                       RJPrtVLTender1
#define  PrtVLTender2                       RJPrtVLTender2
#define  PrtVLTipPaidOut                    RJPrtVLTipPaidOut
#define  PrtVLTotal                         RJPrtVLTotal
#define  PrtVLTrail                         RJPrtVLTrail
#define  PrtVLTray                          RJPrtVLTray
#define  PrtVLPLUBuild                      RJPrtVLPLUBuild
#define  PrtVSAmtMnem                       RJPrtVSAmtMnem
#define  PrtVSAmtPerMnem                    RJPrtVSAmtPerMnem
#define  PrtVSChgTips                       RJPrtVSChgTips
#define  PrtVSCoupon                        RJPrtVSCoupon
#define  PrtVSDeptPlu                       RJPrtVSDeptPlu
#define  PrtVSFCTotal                       RJPrtVSFCTotal
#define  PrtVSGetMDC                        RJPrtVSGetMDC
#define  PrtVSGetMode                       RJPrtVSGetMode
#define  PrtVSSevTotal                      RJPrtVSSevTotal
#define  PrtVSSevTotalPost                  RJPrtVSSevTotalPost
#define  PrtVSTender                        RJPrtVSTender
#define  PrtVSTipsPO                        RJPrtVSTipsPO
#define  PrtVSTotal                         RJPrtVSTotal
#define  PrtVSTotalAudact                   RJPrtVSTotalAudact
#define  usPrtRJColumn                      RJusPrtRJColumn
#define  usPrtVLColumn                      RJusPrtVLColumn
#define  PrtPowerDownLog                    RJPrtPowerDownLog
#define  PrtDflModSeatNo                    RJPrtDflModSeatNo
#define  PrtDflModSeatForm                  RJPrtDflModSeatForm
#define  PrtGetSISymSales                   RJPrtGetSISymSales
#define  PrtGetSISymSalesUS                 RJPrtGetSISymSalesUS
#define  PrtGetSISymSalesCanada             RJPrtGetSISymSalesCanada
#define  PrtGetSISymSalesIntl               RJPrtGetSISymSalesIntl
#define  PrtGetSISym                        RJPrtGetSISym
#define  PrtGetSISymDisc                    RJPrtGetSISymDisc
#define  PrtGetSISymItemDiscUS              RJPrtGetSISymItemDiscUS
#define  PrtGetSISymItemDiscCanada          RJPrtGetSISymItemDiscCanada
#define  PrtGetSISymItemDiscIntl            RJPrtGetSISymItemDiscIntl
#define  PrtGetSISymRegDiscUS               RJPrtGetSISymRegDiscUS
#define  PrtGetSISymRegDiscIntl             RJPrtGetSISymRegDiscIntl
#define  PrtGetSISymCoupon                  RJPrtGetSISymCoupon
#define  PrtGetSISymCouponUS                RJPrtGetSISymCouponUS
#define  PrtGetSISymCouponCanada            RJPrtGetSISymCouponCanada
#define  PrtGetSISymCouponIntl              RJPrtGetSISymCouponIntl
#define  PrtCheckTaxSystem                  RJPrtCheckTaxSystem
#define  PrtRJPerDiscSISym                  RJPrtRJPerDiscSISym
#define  PrtDflItemsEx                      RJPrtDflItemsEx
#endif
#endif