/*========================================================================*\
||                                                                        ||
||        *=*=*=*=*=*=*=*=*                                               ||
||        *  NCR 2170     *             NCR Corporation, E&M OISO         ||
||     @  *=*=*=*=*=*=*=*=*  0             (C) Copyright, 1992            ||
||    <|\/~               ~\/|>                                           ||
||   _/^\_                 _/^\_                Release 1.0               ||
||                                                                        ||
\*========================================================================*/
/*------------------------------------------------------------------------*\
:   Title              : NCR 2170 Header Definition                        :
:   Category           : SUPER & PROGRAM MODE,ECR 2170                     :
:   Program Name       : uifpgex.h                                         :
:  ----------------------------------------------------------------------  :
:                      : YY-MM-DD   Ver.Rev          Comments              :
:   Program Written    : 92-05-14 : 00.00.00     :                         :
:   Update Histories   :          :              :                         :
:                      :          :              :                         :
\*------------------------------------------------------------------------*/
/*------------------------------------------------------------------------*\
:   PVCS ENTRY
:    $Revision$
:    $Date$
:    $Author$
:    $Log$
\*------------------------------------------------------------------------*/

#include "mldmenu.h"
/*------------------------------------------------------------------------*\

            E X T E R N     D E F I N T I O Ns

\*------------------------------------------------------------------------*/

/* Define Control Data Save Area */

/* Define UifPGEnter() Function */

extern  UIMENU CONST aPGEnter[];

/* Define Key Sequence */

extern  UISEQ CONST  aszSeqPGFSC_P1[];
extern  UISEQ CONST  aszSeqPGFSC_P2[];
extern  UISEQ CONST  aszSeqPGFSC_P3[];
extern  UISEQ CONST  aszSeqPGFSC_P4[];
extern  UISEQ CONST  aszSeqPGFSC_P5[];

