#define	__PLUPRCGP_H
#ifndef	__PLUPRCGP_H

#define		ExeInitialize				ExeInitialize_XGP
#define		ExeFinalize					ExeFinalize_XGP
#define		ExeCreateFile				ExeCreateFile_XGP
#define		ExeDeleteFile				ExeDeleteFile_XGP
#define		ExeClearFile				ExeClearFile_XGP
#define		ExeSenseFile				ExeSenseFile_XGP
#define		ExeOpenMirror				ExeOpenMirror_XGP
#define		ExeCloseMirror				ExeCloseMirror_XGP
#define		ExeEnterCritMode			ExeEnterCritMode_XGP
#define		ExeExitCritMode				ExeExitCritMode_XGP
#define		ExeKillCritMode				ExeKillCritMode_XGP
#define		ExeAddRecord				ExeAddRecord_XGP
#define		ExeAddRecordIn				ExeAddRecordIn_XGP
#define		ExeReplaceRecord			ExeReplaceRecord_XGP
#define		ExeReplaceRecordIn			ExeReplaceRecordIn_XGP
#define		ExeChangeRecord				ExeChangeRecord_XGP
#define		ExeChangeRecordIn			ExeChangeRecordIn_XGP
#define		ExeDeleteRecord				ExeDeleteRecord_XGP
#define		ExeDeleteRecordIn			ExeDeleteRecordIn_XGP
#define		ExeDeleteReserved			ExeDeleteReserved_XGP
#define		ExeResetReserved			ExeResetReserved_XGP
#define		ExeRewriteReserved			ExeRewriteReserved_XGP
#define		ExeCancelReserved			ExeCancelReserved_XGP
#define		ExeAppendMainte				ExeAppendMainte_XGP
#define		ExePurgeMainte				ExePurgeMainte_XGP
#define		ExeApplyMainte				ExeApplyMainte_XGP
#define		ExeRemoveMainte				ExeRemoveMainte_XGP
#define		ExeModifyMainte				ExeModifyMainte_XGP
#define		ExeReadMainte				ExeReadMainte_XGP
#define		ExeAddMainte				ExeAddMainte_XGP
#define		ExeReadRecord				ExeReadRecord_XGP
#define		ExeReserveRecord			ExeReserveRecord_XGP
#define		ExeReportRecord				ExeReportRecord_XGP
#define		ExeReadBlock				ExeReadBlock_XGP
#define		ExeWriteBlock				ExeWriteBlock_XGP
#define		ExeSeekBlock				ExeSeekBlock_XGP
#define		ExeUpdateRecord				ExeUpdateRecord_XGP
#define		ExeInformStatus				ExeInformStatus_XGP
#define		ExeSetIndexFileId			ExeSetIndexFileId_XGP
#define		MnpInitialize				MnpInitialize_XGP
#define		MnpFinalize					MnpFinalize_XGP
#define		MnpCreateFile				MnpCreateFile_XGP
#define		MnpDeleteFile				MnpDeleteFile_XGP
#define		MnpClearFile				MnpClearFile_XGP
#define		MnpGetFileInfo				MnpGetFileInfo_XGP
#define		MnpAddRecord				MnpAddRecord_XGP
#define		MnpDeleteRecord				MnpDeleteRecord_XGP
#define		MnpReadRecord				MnpReadRecord_XGP
#define		MnpBeginLookUp				MnpBeginLookUp_XGP
#define		MnpEndLookUp				MnpEndLookUp_XGP
#define		MnpReadFile					MnpReadFile_XGP
#define		MnpWriteFile				MnpWriteFile_XGP
#define		MnpSeekFile					MnpSeekFile_XGP
#define		MnpGetLookUp				MnpGetLookUp_XGP
#define		MnpModifyRecord				MnpModifyRecord_XGP
#define		MnpPeekRecord				MnpPeekRecord_XGP
#define		MnpRemoveRecord				MnpRemoveRecord_XGP
#define		MnpKeepFilePtr				MnpKeepFilePtr_XGP
#define		MnpMoveFilePtr				MnpMoveFilePtr_XGP
#define		MnpGetFilePtr				MnpGetFilePtr_XGP
#define		MnpSetFilePtr				MnpSetFilePtr_XGP
#define		MnpQInfoTable				MnpQInfoTable_XGP
#define		MnpOpenMirror				MnpOpenMirror_XGP
#define		MnpCloseMirror				MnpCloseMirror_XGP
#define		MnpIsMirrorFile				MnpIsMirrorFile_XGP
#define		MnpFileOfMirror				MnpFileOfMirror_XGP
#define		PhyOpenFile					PhyOpenFile_XGP
#define		PhyCreateFile				PhyCreateFile_XGP
#define		PhyDeleteFile				PhyDeleteFile_XGP
#define		PhyClearFile				PhyClearFile_XGP
#define		PhyOpenFile					PhyOpenFile_XGP
#define		PhyAuditFile				PhyAuditFile_XGP
#define		PhyReadFile					PhyReadFile_XGP
#define		PhyWriteFile				PhyWriteFile_XGP
#define		PhyCloseFile				PhyCloseFile_XGP
#define		PhyGetInfo					PhyGetInfo_XGP
#define		PhyUpdateInfo				PhyUpdateInfo_XGP
#define		PhyReadRecord				PhyReadRecord_XGP
#define		PhyWriteRecord				PhyWriteRecord_XGP
#define		PhyExamOccupied				PhyExamOccupied_XGP
#define		PhySetUpOccupied			PhySetUpOccupied_XGP
#define		PhySearchVacant				PhySearchVacant_XGP
#define		PhySearchOccupied			PhySearchOccupied_XGP

#endif	

