//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NewLayout.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED			    100
#define IDR_MAINFRAME                   128
#define IDR_NEWLAYTYPE                  129
#define IDS_POPUP_EDITBUTTON            130
#define IDR_CONTEXTMENU                 130
#define IDS_POPUP_DELETEBUTTON          131
#define IDD_EDIT_BUTTONCTRL             131
#define IDS_POP_SETWINDOW               132
#define IDS_POPUP_GENERATE              133
#define IDD_EDIT_WINDOWCTRL             133
#define IDS_POPUP_REVERSE_GENERATE      134
#define IDD_DIALOG3                     134
#define IDS_POPUP_COMPILE               135
#define IDS_STATIC_DIALOG1_BUTTONCAPTION 136
#define IDS_STATIC_DIALOG1_TEXTCOLOR    137
#define IDS_STATIC_DIALOG1_BUTTONCOLOR  138
#define IDS_STATIC_DIALOG1_BUTTON_FSC   139
#define IDS_STATIC_DIALOG2_WINDOWCAPTION 140
#define IDS_STATIC_DIALOG2_WINDOWNAME   141
#define IDS_STATIC_DIALOG2_TEMPLATE     142
#define IDD_P03_BOX                     142
#define IDD_DIALOG4                     143
#define IDS_ENTPLUNUM                   143
#define IDD_DIALOG5                     144
#define IDS_PLUKEY                      144
#define IDD_WINDOW_LIST                 144
#define IDS_ENTEXTFSC                   145
#define IDS_DEPTKEY                     146
#define IDD_DIALOG6                     147
#define IDS_PRINTMOD                    147
#define IDD_EDIT_TEXTCTRL               147
#define IDS_PRINTMOD_DR                 148
#define IDS_ADJECTIVE                   149
#define IDS_ADJECTIVE_DR                150
#define IDD_PO3_MODEENTRY               151
#define IDS_TENDER                      151
#define IDS_TENDER_DR                   152
#define IDD_KEYPADENTRY                 153
#define IDS_FOREIGNCUR                  153
#define IDS_FOREIGNCUR_DR               154
#define IDS_TOTAL                       155
#define IDS_TOTAL_DR                    156
#define IDS_ADDCHECK                    157
#define IDS_ADDCHECK_DR                 158
#define IDS_ITEM_DISC_SURCH             159
#define IDR_EXIT_TESTER                 159
#define IDS_ITEM_DISC_SURCH_DR          160
#define IDI_ICON1                       160
#define IDS_TRAN_DISC_SURCH             161
#define IDS_TRAN_DISC_SURCH_DR          162
#define IDS_TAXMOD                      163
#define IDC_CURSOR1                     163
#define IDS_TAXMOD_DR                   164
#define IDS_POD                         165
#define IDS_POD_DR                      166
#define IDS_CHARGETIPS                  167
#define IDD_CHANGE_LANGUAGE             167
#define IDS_CHARGETIPS_DR               168
#define IDS_PRESET_CASH                 169
#define IDS_PRESET_CASH_DR              170
#define IDD_DLG_DEFAULTS                170
#define IDS_DIRECTSHIFT                 171
#define IDS_DIRECTSHIFT_DR              172
#define IDS_COUPONKEY                   173
#define IDS_COUPONKEY_DR                174
#define IDS_CONTROLSTRING               175
#define IDS_CONTROLSTRING_DR            176
#define IDS_SEATNUM                     177
#define IDS_SEATNUM_DR                  178
#define IDS_ASK                         179
#define IDS_ASK_DR                      180
#define IDS_PRICELEVEL                  181
#define IDS_PRICELEVEL_DR               182
#define IDS_MODEKEY                     183
#define IDS_SELECTMODE                  184
#define IDS_NUMPADKEY                   185
#define IDS_SELECTNUM                   186
#define IDS_RANGE_ERR                   187
#define IDS_LOCK                        188
#define IDS_REGISTER                    189
#define IDS_SUPERVISOR                  190
#define IDS_PROGRAM                     191
#define IDS_OVERLAP_ERR                 192
#define IDS_WINDOW_ERR                  193
#define IDS_TEXTEXIST                   194
#define IDS_TEXTHEIGHT_ERR              195
#define IDS_TEXT_ERR                    196
#define IDS_BTNEXIST                    197
#define IDS_DUP_TEXT                    198
#define IDS_WIN_INVALID                 199
#define IDS_NOT_SUP                     200
#define IDS_CPNOTFOUND                  201
#define IDS_NOTKBLIST                   202
#define IDS_DLLNF                       203
#define IDS_NOTSUBLANG                  204
#define IDS_SPACE                       205
#define IDS_BTNEXISTS                   206
#define IDC_CURSOR2                     207
#define IDD_DLG_SUBWIN                  208
#define IDD_DLG_GROUPS                  209
#define IDS_NO_SEL_GRP                  210
#define IDS_DEL_DEFGRP                  211
#define IDS_DUP_GRPNAME                 212
#define IDS_RETLOM                      213
#define IDS_WIN_NF                      214
#define IDS_EMP_GRPNAME                 215
#define IDS_EDIT_DEFGRP                 216
#define IDS_DEFGRP_DESC                 217
#define IDS_DEFGRP_NAME                 218
#define IDS_ATTRIBUTES                  219
#define IDS_REG_ERR                     220
#define IDS_WINITEM                     221
#define IDS_SUBWINITEM                  222
#define IDS_GROUPID                     223
#define IDS_GRP_IN_USE                  224
#define IDD_DLG_OEP                     225
#define IDS_OEP_ERR                     226
#define IDS_LANG_CHINESE                227
#define IDS_LANG_ENGLISH                228
#define IDS_LANG_FRENCH                 229
#define IDS_LANG_GERMAN                 230
#define IDS_LANG_GREEK                  231
#define IDS_LANG_ITALIAN                232
#define IDS_LANG_JAPANESE               233
#define IDS_LANG_RUSSIAN                234
#define IDS_LANG_SPANISH                235
#define IDS_TXT_SING_RCT_MAIN           236
#define IDS_TXT_MULTI_1                 237
#define IDS_TXT_MULTI_2                 238
#define IDS_TXT_MULTI_3                 239
#define IDS_TXT_REC_NOTUSED_1           240
#define IDS_TXT_REC_NOTUSED_2           241
#define IDS_TXT_LEAD_THRU               242
#define IDS_TXT_DESC                    243
#define IDS_TXT_SING_SUB                244
#define IDS_TXT_SING_SCROLL             245
#define IDS_TXT_CLOCK                   246
#define IDS_TXT_SUP_PROG                247
#define IDS_CMDLINE_LANG_NF             248
#define IDS_CURS_POS                    249
#define IDS_HIDE_RULERS                 249
#define IDS_SHOW_RULERS                 250
#define IDR_TREE_MENU                   251
#define IDS_LBL_INVALID                 251
#define IDD_DLG_ACTIVEWND               252
#define IDS_GRPWND_AVTIVE               252
#define IDD_DLG_WINLABEL                253
#define IDS_SET_ICONDIR_MSG             253
#define IDD_EDIT_LABELCTRL              253
#define IDS_ICONDIR_ERR                 254
#define IDD_DLG_FILESUMMARY             255
#define IDS_ICONDIR_SEL_MSG             255
#define IDS_STRING_SUN                  256
#define IDD_DIALOG8                     256
#define IDS_STRING_MON                  257
#define IDS_STRING_TUE                  258
#define IDS_STRING_WED                  259
#define IDS_STRING_THU                  260
#define IDS_STRING_FRI                  261
#define IDS_STRING_SAT                  262
#define IDS_STRING_JAN                  263
#define IDS_STRING_FEB                  264
#define IDS_STRING_MAR                  265
#define IDS_STRING_APR                  266
#define IDS_STRING_MAY                  267
#define IDS_STRING_JUN                  268
#define IDS_STRING_JUL                  269
#define IDS_STRING_AUG                  270
#define IDS_STRING_SEP                  271
#define IDS_STRING_OCT                  272
#define IDS_STRING_NOV                  273
#define IDS_STRING_DEC                  274
#define IDS_FILEVER_MSG                 275
#define IDS_WND_DEL_CONFIRM             276
#define IDS_STRING_GRIDS                277
#define IDS_USR_DSM                     278
#define IDS_ERR_PLUNO                   279
#define IDS_ENTPLUGROUP                 280
#define IDS_LANG_KOREAN                 281
#define IDS_ORDER_DEC                   282
#define IDS_ORDER_DEC_DR                283
#define IDS_GIFT_CARD_DR                284
#define IDS_GIFT_CARD                   285
#define IDS_ISSUE                       286
#define IDS_VOID_ISSUE                  287
#define IDS_RELOAD                      288
#define IDS_VOID_RELOAD                 289
#define IDS_BALANCE                     290
#define IDS_RETURN                      291
#define IDS_VOID_RETURN                 292
#define IDS_DOC_LAUNCH                  293
#define IDS_DOC_LAUNCH_DR               294
#define IDS_ENTWINID                    295
#define IDS_WINID                       296
#define IDS_FREEDOMPAY                  297
#define IDD_DLG_GROUP_PERMISSIONS       298
#define IDS_VOIDRETURN                  299
#define IDS_VOIDRETURN_DR               300
#define IDD_DLG_OEP_TABLE               301
#define IDD_P03_BUTTON_ACTION           302
#define IDD_EDIT_LISTBOXCTRL            303
#define IDS_ENTPLUGROUP_DR              304
#define IDS_STRING_ADJ_LOG_EQUAL        305
#define IDS_STRING_ADJ_LOG_LESS         306
#define IDS_STRING_ADJ_LOG_GREATER      307
#define IDS_TXT_SING_CUST_DISP          308
#define IDS_TXT_LEADTHRU_CUST_DISP      309
#define IDS_TXT_CLOCK_CUST_DISP         310
#define IDS_ENTOEPTABLEROW              311
#define IDS_TXT_OEP_CUST_DISP           312
#define IDC_EDIT_CAPTION                1000
#define IDC_STATIC_CAPTION              1001
#define IDC_COMBO_TEXTCOLOR             1002
#define IDC_STATIC_TEXTCOLOR            1003
#define IDC_COMBO_BGCOLOR               1004
#define IDC_EDIT_WIN_NAME               1004
#define IDC_STATIC_BGCOLOR              1005
#define IDC_STATIC_WIN_NAME             1005
#define IDC_STATIC_WIN_TEMPLATE         1006
#define IDC_STATIC_WIN_CAPTION          1007
#define IDC_EDIT_WIN_CAPTION            1008
#define IDC_DIALOG3_SHAPE_RECT          1011
#define IDC_DIALOG3_SHAPE_ELIPSE        1012
#define IDC_DIALOG3_SHAPE_ROUNDRECT     1013
#define IDC_STATIC_SHAPE                1014
#define IDC_STATIC_DIALOG3_PATTERN_NONE 1015
#define IDC_STATIC_DIALOG3_PATTERN_HORIZ 1016
#define IDC_STATIC_DIALOG3_PATTERN_VERT 1017
#define IDC_STATIC_DIALOG3_PATTERN      1018
#define IDC_DIALOG1_SHAPE_RECT          1019
#define IDC_DIALOG1_SHAPE_ELIPSE        1020
#define IDC_DIALOG1_SHAPE_ROUNDRECT     1021
#define IDC_STATIC_DIALOG1_PATTERN_NONE 1022
#define IDC_STATIC_DIALOG1_PATTERN_HORIZ 1023
#define IDC_STATIC_DIALOG1_PATTERN_VERT 1024
#define IDS_POPUP_CONTROL_RECEIT        1025
#define IDC_COMBO_FONTSIZE              1025
#define IDS_POPUP_CONTROL_LEADTHRU      1026
#define IDC_STATIC_DIALOG1_FONTSIZE     1027
#define IDC_BUTTON_TEXTCOLOR            1028
#define IDC_BUTTON_FACECOLOR            1029
#define IDC_STATIC_SHOW_TEXTCOLOR       1030
#define IDC_STATIC_SHOW_FACECOLOR       1031
#define IDC_BUTTON_ASSIGN_ACTION        1032
#define IDC_EDIT_DIALOG2_WIDTH          1033
#define IDC_EDIT_DIALOG2_HEIGHT         1034
#define IDC_STATIC_DIALOG1_ACTION       1034
#define IDC_EDIT1                       1035
#define IDC_LIST_DIALOG5_WINDOWS        1036
#define IDC_STATIC_DIALOG1_WIDTH        1038
#define IDC_STATIC_DIALOG1_HEIGHT       1039
#define IDC_COMBO_DIALOG1_WIDTH         1040
#define IDC_COMBO_DIALOG1_HEIGHT        1041
#define IDC_STATIC_DIALOG2_HEIGHT       1044
#define IDC_STATIC_DIALOG2_WIDTH        1045
#define IDC_COMBO_DIALOG2_WIDTH         1046
#define IDC_COMBO_DIALOG2_HEIGHT        1047
#define IDC_COMBO_DIALOG2_LEADING       1048
#define IDC_DIALOG5_SHOWPROP            1048
#define IDC_STATIC_DIALOG2_LEADING      1049
#define IDC_STATIC_DIALOG2_FRAME_BUTTON 1050
#define IDC_COMBO_DIALOG2_NO_ROWS       1051
#define IDC_COMBO_DIALOG2_NO_COLS       1052
#define IDC_STATIC_DIALOG2_NO_ROWS      1053
#define IDC_STATIC_DIALOG2_NO_COLS      1054
#define IDC_DIALOG2_BUTTON_COLOR        1055
#define IDC_DIALOG6_BUTTON_COLOR        1056
#define IDC_STATIC_DIALOG2_NO_COLS2     1056
#define IDC_STATIC_DIALOG6_NO_ROWS      1057
#define IDC_STATIC_DIALOG6_NO_COLS      1058
#define IDC_COMBO_DIALOG6_NO_ROWS       1059
#define IDC_COMBO_DIALOG6_NO_COLS       1060
#define IDC_DIALOG6_COMBO_FUNCTION      1061
#define IDC_ENTRY_SPIN                  1063
#define IDC_RADIO_POPUP                 1064
#define IDC_RADIO_VIRTUAL               1065
#define IDC_STATIC_WINSTYLE             1068
#define IDD_P03_RECEIPT                 1071
#define IDC_COMBO_LANGUAGE              1079
#define IDC_BUTTON_DEF_BTNCOLOR         1080
#define IDC_BUTTON_DEF_FONT             1081
#define IDC_BUTTON_DEFWINCOLOR          1082
#define IDC_BUTTON_DEF_TEXTWINCOLOR     1083
#define IDC_STATIC_SHOW_WINCOLOR        1084
#define IDC_STATIC_SHOW_TEXTWINCOLOR    1085
#define IDC_BUTTON_DEF_FONTCOLOR        1086
#define IDC_STATIC_SAMPLE               1092
#define IDC_STATIC_DIALOGDEF_WIDTH      1093
#define IDC_STATIC_DIALOGDEF_HEIGHT     1094
#define IDC_COMBO_DIALOGDEF_WIDTH       1095
#define IDC_COMBO_DIALOGDEF_HEIGHT      1096
#define IDC_STATIC_DIALOGDEF_PATTERN    1097
#define IDC_DEF_SHAPE_RECT              1098
#define IDC_STATIC_DEF_PATTERN_NONE     1101
#define IDC_DEF_SHAPE_ELIPSE            1104
#define IDC_DEF_SHAPE_ROUNDRECT         1105
#define IDC_STATIC_DEF_PATTERN_HORIZONTAL 1106
#define IDC_STATIC_DEF_PATTERN_VERTICAL 1107
#define IDC_RADIO_WINDEF                1115
#define IDC_RADIO_DOCDEF                1116
#define IDC_BUTTONRESET                 1117
#define IDC_RADIO_USEWINDEF             1118
#define IDC_RADIO_USECUSTOM             1119
#define IDC_RADIO_CUST                  1120
#define IDC_RADIO_DEF                   1121
#define IDC_SETBTNFONT                  1121
#define IDC_EDIT_ICONFILENAME           1122
#define IDC_TREE1                       1123
#define IDC_COMBO_GROUP                 1126
#define IDC_EDIT_GRP_NAME               1127
#define IDC_EDIT_GRP_DESC               1128
#define IDC_LIST_GROUPS                 1129
#define IDC_EDIT_BUTTON                 1130
#define IDC_DELETE_BUTTON               1131
#define IDC_SUBMIT                      1132
#define IDC_RADIO_ADD                   1136
#define IDC_RADIO_EDIT                  1137
#define IDC_BTN_EDITFONT                1138
#define IDC_COMBO_NO_PICKS              1139
#define IDC_RADIO_HORIZONTAL            1140
#define IDC_RADIO_VERTICAL              1141
#define IDC_RADIO_CAP_LEFT              1142
#define IDC_RADIO_CAP_CENTER            1143
#define IDC_RADIO_CAP_RIGHT             1144
#define IDC_RADIO_CAP_TOP               1145
#define IDC_RADIO_CAP_MIDDLE            1146
#define IDC_RADIO_CAP_BOTTOM            1147
#define IDC_RADIO_CAP_LEFT2             1148
#define IDC_RADIO_CAP_CENTER2           1149
#define IDC_RADIO_CAP_RIGHT2            1150
#define IDC_RADIO_CAP_TOP2              1151
#define IDC_RADIO_CAP_MIDDLE2           1152
#define IDC_RADIO_CAP_BOTTOM2           1153
#define IDC_CHECK_CUST_CAP              1154
#define IDC_OEP_SHAPE_RECT              1156
#define IDC_OEP_SHAPE_ELIPSE            1157
#define IDC_OEP_SHAPE_ROUNDRECT         1158
#define IDC_OEP_PATTERN_NONE            1159
#define IDC_OEP_PATTERN_HORIZ           1160
#define IDC_OEP_PATTERN_VERT            1161
#define IDC_COMBO_OEP_WIDTH             1162
#define IDC_COMBO_OEP_HEIGHT            1163
#define IDC_OEP_FACECOLOR               1164
#define IDC_STATIC_SHOW_OEP_FACECOLOR   1165
#define IDC_OEP_WINCOLOR                1170
#define IDC_STATIC_SHOW_OEP_WINCOLOR    1171
#define IDC_OEP_EDIT_BTNFONT            1172
#define IDC_OEP_EDIT_WINFONT            1173
#define IDC_COMBO_OEP_BTN_ACROSS        1174
#define IDC_COMBO_OEP_BTN_DOWN          1175
#define IDC_STATIC_OEP_HEIGHT           1176
#define IDC_STATIC_OEP_WIDTH            1177
#define IDC_STATIC_OEP_BTN_ACROSS       1180
#define IDC_STATIC_OEP_BTN_DOWN         1181
#define IDC_STATIC_OEP_WIN_WIDTH        1182
#define IDC_STATIC_OEP_WIN_HEIGHT       1183
#define IDC_COMBO_GRPLIST               1184
#define IDC_LIST_GRPWND                 1186
#define IDC_BUTTON_ACTIVATE             1187
#define IDC_BUTTON_SETACTWND            1188
#define IDC_EDIT_LBLCAPTION             1189
#define IDC_EDIT_LBL_ICONFILENAME       1190
#define IDC_RADIO_LBLICON_LEFT          1191
#define IDC_RADIO_LBLICON_CENTER        1192
#define IDC_RADIO_LBLICON_RIGHT         1193
#define IDC_RADIO_LBLICON_TOP           1194
#define IDC_RADIO_LBLICON_MIDDLE        1195
#define IDC_RADIO_LBLICON_BOTTOM        1196
#define IDC_RADIO_LBL_VERTICAL          1197
#define IDC_RADIO_LBL_HORIZONTAL        1198
#define IDC_RADIO_LBLCAP_TOP            1199
#define IDC_RADIO_LBLCAP_MIDDLE         1200
#define IDC_RADIO_LBLCAP_BOTTOM         1201
#define IDC_RADIO_LBLCAP_LEFT           1202
#define IDC_RADIO_LBLCAP_CENTER         1203
#define IDC_RADIO_LBLCAP_RIGHT          1204
#define IDC_COMBO_WINLBL_WIDTH          1205
#define IDC_COMBO_WINLBL_HEIGHT         1206
#define IDC_WINLBL_FACECOLOR            1207
#define IDC_SETWINLBLFONT               1208
#define IDC_EDIT_MINOR                  1209
#define IDC_EDIT_RELEASE                1210
#define IDC_EDIT_MAJOR                  1211
#define IDC_EDIT_SUMMARY                1214
#define IDC_EDIT_PEPFILE                1215
#define IDC_STATIC_MOD1                 1216
#define IDC_STATIC_MOD2                 1217
#define IDC_STATIC_MOD3                 1218
#define IDC_STATIC_MOD4                 1219
#define IDC_STATIC_MOD5                 1220
#define IDC_STATIC_DOT                  1221
#define IDC_STATIC_DOT2                 1222
#define IDC_BUTTON_SETICONDIR           1223
#define IDC_EDIT_ICON_DIR               1224
#define IDC_BUTTON_BROWSE               1225
#define IDC_BUTTON_SETDIR               1226
#define IDC_BUTTONSETDIR                1228
#define IDC_STATIC_BUTTON_ATTRIBUTES    1230
#define IDC_DEFAULT_WINDOW              1231
#define IDC_WEB_BROWSER                 1232
#define IDC_REPORT_SCROLLABLE           1233
#define IDC_CHK_NO_TRANSLATE            1234
#define IDC_CHK_GROUP_SHOWHIDE          1235
#define IDC_EDIT_PREVIEW                1236
#define IDC_DISPLAY_TRANSLATE           1237
#define IDC_DISPLAY_ROLLUP_ENABLE       1238
#define IDC_STATIC_OEP_GroupID          1240
#define IDC_COMBO_OEP_Sort              1244
#define IDC_STATIC_OEP_Sort             1245
#define IDC_STATIC_OEP_IDrange          1248
#define IDC_EDIT1_OEPGroupNumbers       1251
#define IDC_CHECK_IS_COUNTER            1256
#define IDC_CHECK_SPR_REG               1257
#define IDC_CHECK_SPR_SUPR              1258
#define IDC_CHECK_SPR_PROG              1259
#define IDC_CHECK_LABEL_BORDER_SPL      1260
#define IDC_CHECK_LABEL_BORDER_LFT      1261
#define IDC_CHECK_LABEL_BORDER_RHT      1262
#define IDC_CHECK_LABEL_BORDER_TOP      1263
#define IDC_CHECK_LABEL_BORDER_BOT      1264
#define IDC_CHECK_AUTO_OEP              1265
#define IDC_CHECK_SPECIAL_OEP           1266
#define IDC_EVENTTRIGGER_ENABLED        1269
#define IDC_EVENTTRIGGER_ORDERDEC       1270
#define IDC_CHECK_CONNENGINE            1271
#define IDC_EDIT_CONNENGINE_BUTTON_NAME 1272
#define IDC_STATIC_CONNENGINE           1273
#define IDC_STATIC_CONNENGINE_BUTTON_NAME 1274
#define IDC_CHECK1                      1275
#define IDC_CHECK2                      1276
#define IDC_CHECK3                      1277
#define IDC_CHECK4                      1278
#define IDC_CHECK5                      1279
#define IDC_CHECK6                      1280
#define IDC_CHECK7                      1281
#define IDC_CHECK8                      1282
#define IDC_EDIT_CONTROL_NAME           1284
#define IDC_BTN_CHECK_ALL               1285
#define IDC_BTN_CHECK_NONE              1286
#define IDC_BTN_CHECK_INVERT            1287
#define IDC_BTN_GROUP_PERMISSIONS       1288
#define IDC_BTN_SET_GROUP_PERMISSION    1290
#define IDC_OEP_ICON_BROWSE_BTN         1292
#define IDC_OEP_ICON_HOR_LEFT           1293
#define IDC_OEP_ICON_HOR_CENTER         1294
#define IDC_OEP_ICON_HOR_RIGHT          1295
#define IDC_OEP_ICON_VERT_TOP           1296
#define IDC_OEP_ICON_VERT_MIDDLE        1297
#define IDC_OEP_ICON_VERT_BOTTOM        1298
#define IDC_OEP_ICON_FILENAME_EDIT      1299
#define IDC_LIST_ACTION                 1303
#define IDC_STATIC_CURRENTACTION        1305
#define IDC_STATIC_CURRENTACTIONNAME    1305
#define IDC_CHECK_SPR_AUTOCLOSE         1306
#define IDC_CHECK9                      1331
#define IDC_CHECK10                     1332
#define IDC_CHECK11                     1333
#define IDC_CHECK12                     1334
#define IDC_CHECK13                     1335
#define IDC_CHECK14                     1336
#define IDC_CHECK15                     1337
#define IDC_CHECK16                     1338
#define IDC_CHECK17                     1339
#define IDC_CHECK18                     1340
#define IDC_CHECK19                     1341
#define IDC_CHECK20                     1342
#define IDC_CHECK21                     1343
#define IDC_CHECK22                     1344
#define IDC_CHECK23                     1345
#define IDC_CHECK24                     1346
#define IDC_CHECK25                     1347
#define IDC_CHECK26                     1348
#define IDC_CHECK27                     1349
#define IDC_CHECK28                     1350
#define IDC_CHECK29                     1351
#define IDC_CHECK30                     1352
#define IDC_CHECK31                     1353
#define IDC_CHECK32                     1354
#define IDC_CHECK_SCRIPTING             1355
#define IDC_EDIT_BROWSER_URL            1356
#define IDC_CHECK_FILTER_ADJ            1357
#define IDC_CHECK_FILTER_VALUE          1358
#define IDC_CHECK_FILTER_ADJ_ZERO       1359
#define IDC_COMBO_FILTER_VALUE_LOGIC    1360
#define IDC_RADIO_OEP_SPL_PREAUTH       1361
#define IDC_RADIO_OEP_SPL_REASONCODE    1362
#define IDC_RADIO_OEP_SPL_AUTOCOUPON    1363
#define IDC_RADIO_OEP_SPL_OPENCHECK     1364
#define IDD_P03_EXTEND_MSG2             20309
#define IDD_P03_DEPTIN2                 20314
#define IDD_P03_DEPTSPIN2               20315
#define IDD_P03_DEF_KEYPAD              20438
#define IDD_P03_NUMBERPAD               20490
#define IDD_P03_MINIMIZE                20491
#define IDD_P03_CLEAR                   20492
#define IDD_P03_MENUMODEKEY             20493
#define IDD_P03_P1                      20536
#define IDD_P03_P2                      20537
#define IDD_P03_P3                      20538
#define IDD_P03_P4                      20539
#define IDD_P03_P5                      20540
#define IDD_P03_PLU_GROUP               20541
#define IDD_P03_OEP_TABLE_ROW           20542
#define IDS_POP_WINDOW_LIST             32773
#define ID_APP_PROPERTIES               32774
#define IDS_POP_ADD_TEXT_WINDOW         32775
#define ID_POP1_REMOVECONTROL           32779
#define ID_FILE_TEST                    32782
#define ID_VIEW_SCALETOFITWINDOW        32783
#define ID_POP_CLOSETESTWINDOW          32784
#define ID_BUTTON32787                  32787
#define ID_BUTTON32788                  32788
#define ID_BUTTON32789                  32789
#define IDS_POPUP_COPY                  32790
#define IDS_POPUP_CUT                   32791
#define IDS_POPUP_PASTE                 32792
#define IDS_POPUP_COPYWINDOW            32793
#define IDS_POPUP_CUTWINDOW             32794
#define IDS_POPUP_PASTEWINDOW           32795
#define IDS_ADD_GROUP                   32796
#define ID_VIEW_RESOLUTION_800          32800
#define ID_VIEW_RESOLUTION_1024         32801
#define ID_VIEW_RESOLUTION_1280         32802
#define ID_VIEW_RESOLUTION_1440         32803
#define ID_VIEW_RESOLUTION_1920         32804
#define ID_VIEW_LANGUAGE                32805
#define ID_POP1_CHANGEDEFAULTS          32807
#define IDS_POPUP_EDITTEXT              32808
#define IDS_POPUP_EDITWIN               32809
#define IDS_POPUP_EDITBTN               32810
#define IDS_POP_SETSUBWIN               32811
#define ID_VIEW_DOCUMENTTREE            32812
#define IDS_POPUP_EDITSUBWIN            32813
#define ID_POP1_ADDWINDOWGROUP          32814
#define ID_PAINT                        32817
#define ID_FILE_EXPORT                  32818
#define ID_FILE_IMPORT                  32819
#define IDS_POP_SET_OEPWIN              32820
#define ID_POP1_EDIT_OEPWINDOW          32821
#define ID_VIEW_RULERS                  32822
#define ID_TREE_EDIT_WINDOW             32823
#define ID_TREE_DELETE_WINDOW           32824
#define ID_TOGGLE_RULER                 32825
#define ID_POP1_ACTIVE_WINDOW_IN_GROUP  32826
#define ID_POP1__ADDLABEL               32827
#define ID_POP1_EDITLBL                 32828
#define ID_HELP_FILESUMMARY             32829
#define ID_FILE_FILESUMMARY             32830
#define ID_TOOLBAR_PROPERTIES           32831
#define ID_TOOLBAR_WINGROUP             32832
#define ID_TOOLBAR_LANG                 32833
#define ID_TOOLBAR_ACTIVEWND            32834
#define ID_TOOLBAR_DEFAULTS             32835
#define ID_TOOLBAR_WND                  32836
#define ID_TOOLBAR_BTL                  32837
#define ID_TOOLBAR_BTN                  32837
#define ID_TOOLBAR_TXT                  32838
#define ID_TOOLBAR_LBL                  32839
#define ID_TOOLBAR_OEP                  32840
#define ID_TOOLBAR_DELETE               32842
#define ID_TOOLBAR_UNDO                 32843
#define ID_TOOLBAR_REDO                 32844
#define ID_POP1_ADDLISTBOX              32845
#define ID_POP1_EDITLISTBOX             32846
#define ID_POP1_ADDEDITBOX              32847
#define ID_POP1_EDITEDITBOX             32848
#define ID_VIEW_RESOLUTION_1680         32849
#define ID_VIEW_RESOLUTION_2560         32850

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        313
#define _APS_NEXT_COMMAND_VALUE         32849
#define _APS_NEXT_CONTROL_VALUE         1362
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
