/*
* ===========================================================================
*       DialogBox ID Definision
*   These definitions are used in the help content files (concepts.rtf,
*   dialogs.rtf, and procedures.rtf) to identify the various topics that are
*   provided in that material.  These defines along with the .rtf files are
*   used by the old help generation workshop which takes the .rtf file and
*   compiles it into the actual help file.  This is not the new html help
*   format but the older, Visual Studio 6.0 help.
* ===========================================================================
*/
#define IDD_A04			2001        /* Set PLU Number on Menu Page          */
#define IDD_A05         2005        /* Set Menu Page Control Table          */
#define IDD_A07         2007        /* Cashier A/B Key Assignment           */
#define IDD_A20         2020        /* Cashier Maintenance                  */
#define IDD_A33         2033        /* Set Control String Table             */
#define IDD_A68         2068        /* PLU Maintenance                      */
#define IDD_A71         2071        /* Set PPI Table                        */
#define IDD_A84         2084        /* Set Rounding Table                   */
#define IDD_A86         2086        /* Set Discount/Surcharge/Bonus % Rates */
#define IDD_A87         2087        /* Set Slip Promotion Header            */
#define IDD_A88         2088        /* Set Sales Promotion Message          */
#define IDD_A89         2089        /* Set Currency Conversion Rate         */
#define IDD_A111        2111        /* Set Tare Table                       */
#define IDD_A114        2114        /* Department Maintenance               */
                                    /*       Department Key       NCR2172   */
#define IDD_A116        2116        /* Set Promotional PLU                  */
#define IDD_A124        2124        /* Set Tax Table                        */
#define IDD_A127        2127        /* Set Tax Rate                         */
#define IDD_A130        2130        /* Set Pig Rule Table          R3.1     */
#define IDD_A133        2133        /* Service Time Parameter Maintenance R3.1     */
#define IDD_A137        2137        /* Set Beverage Dispenser Parameter R3.1*/
#define IDD_A152        2152        /* Employee number assignment           */
#define IDD_A154        2154        /* Set Wage Rate for Job Code  R3.1     */
#define IDD_A160        2160        /* Set Order Entry Prompt Table         */
#define IDD_A161        2161        /* Coupon Maintenance                   */
#define IDD_A162        2162        /* Flexible Drivethru                   */
#define IDD_A170        2170        /* Set Sales Restriction Table of PLU   */
                                    /*                            NCR2172   */
#define IDD_A208        2171        /* Set Boundary Age           NCR2172   */
#define IDD_A209		2174		/* Color Palette                        */
#define IDD_A128        2128        /* ### ADD Saratoga (051900)            */
#define IDD_P72		2273		/* Reason Code mnemonics                */
#define IDD_A156        2274        /* suggested tip amount Maintenance R2.4.1   */
