
/*
* ===========================================================================
*       DialogBox ID Definision
*   These definitions are used in the help content files (concepts.rtf,
*   dialogs.rtf, and procedures.rtf) to identify the various topics that are
*   provided in that material.  These defines along with the .rtf files are
*   used by the old help generation workshop which takes the .rtf file and
*   compiles it into the actual help file.  This is not the new html help
*   format but the older, Visual Studio 6.0 help.
* ===========================================================================
*/
#define IDD_P01         2201        /* Machine Definition Code              */
#define IDD_P02         2202        /* Flexible Memory Assignment           */
#define IDD_P03			2205        /* Function Selection Code              */
#define IDD_P06         2206        /* Program Mode Security Number         */
#define IDD_P08         2208        /* Supervisor Number/Level              */
#define IDD_P09         2209        /* Action Code Security                 */
#define IDD_P10         2210        /* High Amount Lock-out(HALO) Limit     */
#define IDD_P15         2215        /* Preset Amount for Preset Cash Key    */
#define IDD_P17         2217        /* Hourly Activity Time                 */
#define IDD_P18         2218        /* Print Lines on Slip                  */
#define IDD_P20         2220        /* Transaction Mnemonic                 */
#define IDD_P21         2221        /* Lead Trough Message                  */
#define IDD_P22         2222        /* Report Mnemonic                      */
#define IDD_P23         2223        /* Special Mnemonic                     */
#define IDD_P46         2246        /* Adjective Mnemonics                  */
#define IDD_P47         2247        /* Print Modifier Mnemonics             */
#define IDD_P48         2248        /* Major Department Mnemonics           */
#define IDD_P49         2249        /* Automatic Alternative Remote Printer */
#define IDD_P50         2250        /* Assignment Terminal # Installing Shared Printer */
#define IDD_P51         2251        /* Assignment IP Address for KDS NCR2172*/
#define IDD_P54         2254        /* Set Hotel Id and SLD                 */
#define IDD_P57         2257        /* Header Message                       */
#define IDD_P60         2260        /* Total Key Type / Function            */
#define IDD_P62         2262        /* Tender Key Parameter , V3.3          */
#define IDD_P65         2265        /* Multi-Line Display Mnemonics , V3.3  */
#define IDD_P97			2297		/* Terminal Information					*/
#define IDD_P98			2298		/* Tender Key Setup						*/
