/*========================================================================*\
||                                                                        ||
||        *=*=*=*=*=*=*=*=*                                               ||
||        *  NCR 2170     *             NCR Corporation, E&M OISO         ||
||     @  *=*=*=*=*=*=*=*=*  0             (C) Copyright, 1992            ||
||    <|\/~               ~\/|>                                           ||
||   _/^\_                 _/^\_                Release 1.0               ||
||                                                                        ||
\*========================================================================*/
/*------------------------------------------------------------------------*\
:  Title              : Device I/O Configuration                           :
:  Category           : Device Independent I/O, 2170 XINU Operating System :
:  Program Name       : CONF.C                                             :
:  ----------------------------------------------------------------------- :
:  Description                                                             :
:       This file is generated by XINU Configurator, CONFIG.EXE.           :
:       It contains,                                                       :
:                                                                          :
:               1. Device Independent I/O Table                            :
:                                                                          :
:       To modify this file, edit "2170conf" and execute "config.exe". :
:  ----------------------------------------------------------------------- :
:  Compile            : MS-C Ver. 6.00A by Microsoft Corp.                 :
:  Memory Model       : Compact Model                                      :
:  Compile Option     : /c /ACw /Za /W4 /FPa /Gs                           :
:  ----------------------------------------------------------------------- :
:  Update Histories                                                        :
:                       GENERATED FILE: DO NOT EDIT                        :
\*------------------------------------------------------------------------*/

#include <conf.h>
#include <kernel.h>
#include <bios.h>

/* device independent I/O switch */

DEVICE	devtab[NDEVS] = {

/*------------------------------------------------------------------------
 * Format of each entry is:
 *
 * device number, device name,
 * init, open, close,
 * read, write, seek,
 * getc, putc, cntl,
 * port addr, device input vector, device output vector,
 * input interrupt routine, output interrupt routine,
 * device i/o block, minor device number
 *------------------------------------------------------------------------
 */

/* COM is sio on PORT */
0,"sio",
SioInit,SioOpen,SioClose,
SioRead,SioWrite,(short(*)(DEVICE *,unsigned long,...))ioerr,
(short(*)(DEVICE *))ioerr,(short(*)(DEVICE *,char))ioerr,SioCntl,
0,0,0,
(void(*)(short))ioerr,(void(*)(short))ioerr,
NULLPTR,0,

/* ASY is asy on DRIVER */
1,"asy",
AsyInit,AsyOpen,AsyClose,
AsyRead,AsyWrite,(short(*)(DEVICE *,unsigned long,...))ioerr,
(short(*)(DEVICE *))ioerr,(short(*)(DEVICE *,char))ioerr,AsyCntl,
0,0,0,
(void(*)(short))ioerr,(void(*)(short))ioerr,
NULLPTR,0,

/* YAM is yam on DRIVER */
2,"yam",
YamInit,YamOpen,YamClose,
YamRead,YamWrite,(short(*)(DEVICE *,unsigned long,...))ioerr,
(short(*)(DEVICE *))ioerr,(short(*)(DEVICE *,char))ioerr,YamCntl,
0,0,0,
(void(*)(short))ioerr,(void(*)(short))ioerr,
NULLPTR,0,

/* INTERNET is net on DLC */
3,"net",
NetInit,NetOpen,(short(*)(DEVICE *))ioerr,
(short(*)(DEVICE *,void *,short))ioerr,(short(*)(DEVICE *,void *,short))ioerr,(short(*)(DEVICE *,unsigned long,...))ioerr,
(short(*)(DEVICE *))ioerr,(short(*)(DEVICE *,char))ioerr,NetCntl,
0,0,0,
(void(*)(short))ioerr,(void(*)(short))ioerr,
NULLPTR,0,

/* GENERIC is dg on DLC */
4,"",
DgInit,(short(*)(DEVICE *,...))ioerr,DgClose,
DgRead,DgWrite,(short(*)(DEVICE *,unsigned long,...))ioerr,
(short(*)(DEVICE *))ioerr,(short(*)(DEVICE *,char))ioerr,DgCntl,
0,0,0,
(void(*)(short))ioerr,(void(*)(short))ioerr,
NULLPTR,0
};
