//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PCSample.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PCSAMPTYPE                  129
#define IDD_CONNECT_LOGON               130
#define IDD_SET_SERIALPORT              134
#define IDD_CHG_PASSWORD                136
#define IDD_SET_TERMINALNO              139
#define IDD_SET_DATETIME                142
#define IDD_SET_REGNO                   144
#define IDD_SET_CASNO                   145
#define IDD_SET_GCNO                    147
#define IDD_SET_MDEPTNO                 148
#define IDD_SET_DEPTNO                  149
#define IDD_CONNECT_MODEM               150
#define IDD_CONNECT_LAN                 151
#define IDD_RCV_PROGRESS                153
#define IDD_SEND_OP_MSG                 154
#define IDD_PLUASSIGNUPDATE             155
#define IDD_PAGE_CONNECT                157
#define IDD_PAGE_CASHIERACTION          158
#define IDD_PAGE_EMPLOYEECHANGE         159
#define IDD_CESCRAP                     160
#define IDD_PAGE_GUESTCHECK             161
#define IDD_CASHIER_LIST                162
#define IDD_CASHIER_EDIT                163
#define IDD_CASHIER_TAB_ONE             164
#define IDD_CASHIER_TAB_TWO             165
#define IDD_CASHIER_TAB_THREE           166
#define IDD_SELECTACTIVITYLIST          167
#define IDD_CASHIER_SELECT              168
#define IDD_DIALOG_REPORTLIST           169
#define IDC_TEXT_PORT                   1001
#define IDC_TEXT_BAUD                   1002
#define IDC_TEXT_DATABITS               1003
#define IDC_TEXT_PARITY                 1004
#define IDC_TEXT_STOPBITS               1005
#define IDC_PB_SERIALPORT               1006
#define IDC_EDIT_TERMNO                 1007
#define IDC_EDIT_PASSWORD               1008
#define IDC_CB_PORTNO                   1010
#define IDC_CB_BAUD                     1015
#define IDC_CB_DATABITS                 1016
#define IDC_CB_PARITY                   1017
#define IDC_CB_STOPBITS                 1018
#define IDC_EDIT_YEAR                   1023
#define IDC_CB_MONTH                    1026
#define IDC_EDIT_DAY                    1027
#define IDC_CB_WDAY                     1028
#define IDC_EDIT_HOUR                   1029
#define IDC_EDIT_MINUTE                 1030
#define IDC_EDIT_STORENO                1031
#define IDC_EDIT_CASNO                  1033
#define IDC_EDIT_GCNO                   1034
#define IDC_EDIT_MDEPTNO                1035
#define IDC_EDIT_DEPTNO                 1036
#define IDC_EDIT_ATCOMMAND              1037
#define IDC_EDIT_PHONE                  1038
#define IDC_RADIO_PULSE                 1039
#define IDC_RADIO_TONE                  1040
#define IDC_EDIT_TERMNO_LAN             1042
#define IDC_EDIT_IP4                    1042
#define IDC_EDIT_PASSWORD_LAN           1043
#define IDC_EDIT_IP1                    1044
#define IDC_EDIT_IP2                    1045
#define IDC_EDIT_IP3                    1047
#define IDC_EDIT_TERMINAL_NO            1049
#define IDC_EDITTERMNO_LAN              1050
#define IDC_PROGRESS1                   1051
#define IDC_RCVLay_text                 1052
#define IDC_EDIT_HOST_LAN               1053
#define IDC_IP_CONNECT                  1054
#define IDC_HOST_CONNECT                1055
#define IDC_CONNECT_OPT                 1056
#define IDC_EDIT_MSG                    1062
#define IDC_CHECK1                      1063
#define IDC_CHECK2                      1064
#define IDC_CHECK3                      1065
#define IDC_CHECK4                      1066
#define IDC_CHECK5                      1067
#define IDC_CHECK6                      1068
#define IDC_EDIT_PLUNUMBER              1069
#define IDC_BUTTON_FETCHPLU             1070
#define IDC_BUTTON_UPDATEPLU            1071
#define IDC_EDIT_PLU_MNEMONIC           1072
#define IDC_EDIT_PLU_PRICE              1073
#define IDC_EDIT_PLU_GROUPNUMBER        1074
#define IDC_EDIT_PLU_TABLENUMBER        1075
#define IDC_EDIT_PLU_DEPTNUMBER         1076
#define IDC_CHECK7                      1077
#define IDC_BUTTON_DELETEPLU            1078
#define IDC_BTNSTART                    1082
#define IDC_CE_CONNECT                  1082
#define IDC_CE_IPADDRESS                1083
#define IDC_CE_IPPORT                   1084
#define IDC_CE_ACTIONTYPE               1085
#define IDC_CE_EMPLOYEEID               1086
#define IDC_CE_AMOUNT                   1089
#define IDC_CE_COMMAND                  1089
#define IDC_EDITCOMMAND                 1090
#define IDC_CE_NOTIFICATION             1090
#define IDC_CHECKAPPENDCOMMAND          1091
#define IDC_EDITNOTIFICATION            1094
#define IDC_CE_CLEAR                    1094
#define IDC_CHECKAPPENDNOTIFICATION     1095
#define IDC_CE_CLEAR2                   1095
#define IDC_CE_CLEARINCOMING            1095
#define IDC_BTNCLEARNOTIFICATION        1096
#define IDC_CE_TOTALID                  1096
#define IDC_CE_SEND                     1098
#define IDC_CE_MNEMONIC                 1099
#define IDC_CE_JOBCODE                  1100
#define IDC_CE_CHECKNUM                 1101
#define IDC_CE_LOGMSGOUT                1102
#define IDC_CE_LOGMSGIN                 1103
#define IDC_DISCONNECT                  1104
#define IDC_CASHIER_LIST                1105
#define IDC_BUTTON_EDIT_SELECTED        1106
#define IDC_BUTTON_SEND_CHANGES         1107
#define IDC_EDIT_CASHIER_NAME           1107
#define IDC_EDIT_CASHIER_SUPNO          1108
#define IDC_EDIT_CASHIER_TEAMNO         1109
#define IDC_EDIT_CASHIER_GCSTART        1110
#define IDC_EDIT_CASHIER_GCEND          1111
#define IDC_TAB_CASHIER_EDIT_STATUS     1112
#define IDC_TAB_CASHIER_EDIT_A20ST01    1113
#define IDC_TAB_CASHIER_EDIT_A20ST02    1114
#define IDC_TAB_CASHIER_EDIT_A20ST03    1115
#define IDC_TAB_CASHIER_EDIT_A20ST04    1116
#define IDC_TAB_CASHIER_EDIT_A20ST05    1117
#define IDC_TAB_CASHIER_EDIT_A20ST06    1118
#define IDC_TAB_CASHIER_EDIT_A20ST07    1119
#define IDC_TAB_CASHIER_EDIT_A20ST08    1120
#define IDC_TAB_CASHIER_EDIT_A20ST09    1121
#define IDC_TAB_CASHIER_EDIT_A20ST10    1122
#define IDC_TAB_CASHIER_EDIT_A20ST11    1123
#define IDC_TAB_CASHIER_EDIT_A20ST12    1124
#define IDC_EDIT_DB_NAME                1125
#define IDC_LIST1                       1126
#define IDC_CHECK_USE_DATABASE          1127
#define ID_CONNECT_LOGON                32772
#define ID_CONNECT_LOGOFF               32773
#define ID_CONNECT_LOCK_KBD             32774
#define ID_CONNECT_UNLOCK_KBD           32775
#define ID_CONNECT_CHG_PASSWORD         32776
#define ID_READ_REGFIN                  32777
#define ID_READ_REGFIN_PTD              32778
#define ID_READ_EJ                      32779
#define ID_READ_ETK                     32780
#define ID_READ_CPM                     32781
#define ID_READ_SERVICETIME             32782
#define ID_READ_INDFIN                  32783
#define ID_RESET_EOD                    32784
#define ID_RESET_CASHIER                32785
#define ID_RESET_SERVICETIME            32786
#define ID_RESET_INDFIN                 32787
#define ID_RESET_CPM                    32788
#define ID_RESET_EJ                     32789
#define ID_RESET_ETK                    32790
#define ID_RESET_GC_BYGCN               32791
#define ID_RESET_GC_BYCASHIER           32792
#define ID_RESET_GC_FLAG                32793
#define ID_RESET_OPENEDGC               32793
#define ID_PARA_CONFIG                  32796
#define ID_PARA_SET_DATE                32798
#define ID_PARA_SET_REGNO               32799
#define ID_RESET_EJ_OVERRIDE            32800
#define ID_RESET_EJ_NONOVERRIDE         32801
#define ID_WINDOW_CLEAR                 32803
#define ID_READ_CASHIER                 32804
#define ID_READ_GC_BYGCN                32805
#define ID_READ_GC_BYCASHIER            32806
#define ID_READ_HOURLY                  32807
#define ID_READ_DEPT                    32808
#define ID_READ_PLU                     32809
#define ID_READ_COUPON                  32810
#define ID_RESET_PLU                    32811
#define ID_RESET_COUPON                 32812
#define ID_CONNECT_MODEM_ON             32813
#define ID_CONNECT_MODEM_OFF            32814
#define ID_CONNECT_LAN_ON               32815
#define ID_CONECT_LAN_OFF               32816
#define ID_ISSUE_EOD                    32817
#define ID_READ_GC_ALL                  32818
#define ID_BUTTON32821                  32821
#define ID_READ_PLUEX                   32822
#define ID_RCVLAYOUT                    32823
#define ID_RCVLGOFILE                   32824
#define ID_RCVLOGFILE                   32825
#define ID_RCVASSRTLOG                  32826
#define ID_RCVDEBGLOG                   32827
#define ID_EOD_DB                       32828
#define ID_READ_SAV_TOTAL               32829
#define IDD_RECIEVE_SAV_TTL             32830
#define ID_SEND_OP_MESSAGE              32831
#define ID_PARA_UPDATE_PLU              32832
#define ID_BCAST_SUP_AC_PARMS           32833
#define ID_BCAST_ALL_P_AC_PARMS         32834
#define ID_BCAST_PLU_OEP_PARMS          32835
#define ID_RETRIEVE_SYSTEMSTATUS        32836
#define ID_Menu                         32837
#define ID_WINDOW_PRINT                 32838
#define ID_WINDOW_CONNECTENGINE         32839
#define ID_WINDOW_ALWAYSONTOP           32840
#define ID_INSERT_EJ_NOTE               32841
#define ID_SAVE_LOG_TO_FILE             32842
#define ID_PROV_CASHIER                 32843
#define ID_DELASSRTLOG                  32844
#define ID_TOGGLE_SYLK_EXPORT           32845
#define ID_SELECTFROMACTIVITYLIST       32846
#define ID_WINDOW_PRINTLASTREPORT       32847
#define ID_DIAOLOG_REPORTLIST           32848
#define ID_SCAN_FOR_MASTER				32849

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32850
#define _APS_NEXT_CONTROL_VALUE         1128
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
